### ISSUE TITLE
Update base URL for artoolkit.worker.js

### ISSUE THREAD

**Issue by JamesBotterill** [AR-js-org/AR.js#10]
**This is a *bug*?**

Currently the base url in aframe-ar-nft points to the old repro, this needs to be updated to ensure file is downloaded from the new repro. 

Current when attempt to use the aframe-ar-nft version you get a error due to file not being available

The file is loaded without error

**Comment by kalwalt** [comment]
Thank you @JamesBotterill to report this! i will look into it!

**Comment by kalwalt** [comment]
@JamesBotterill i think this happens running the code outside the AR.js folder. We need to fix this. In the meantime can you try to put the artoolkit.worker.js in a folder as `three.js/vendor/jsartoolkit5/js/artoolkit.worker.js`. But not tested.

**Comment by JamesBotterill** [comment]
I've tried this and now ran into another issue. 

I'm attempting to run on github but running into the following error now: 

Uncaught DOMException: Failed to construct 'Worker': Script at 'https://ar-js-org.github.io/AR.js/three.js/vendor/jsartoolkit5/js/artoolkit.worker.js' cannot be accessed from origin 'https://jamesbotterill.github.io'.

From looks this is a CORS issue when using worker.js files.

**Comment by kalwalt** [comment]
yes, i saw this, we need to find another solution. Now i'm trying to inject the worker with a BlobUrl. I will let you know. :slightly_smiling_face:

**Comment by kalwalt** [comment]
@JamesBotterill this codepen should work https://codepen.io/kalwalt/pen/zYGRRYd :smile:
