### ISSUE TITLE
Object upside down on iOS 13 Safari

### ISSUE THREAD

**Issue by renedekat** [AR-js-org/AR.js#100]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
When scanning the HIRO sample image from your repository using the demo URL for markers on iOS13, the dinosaur is upside down. No matter at what position I have the scanned image. 
See screenshot:
![IMG_1217](https://user-images.githubusercontent.com/8975204/80858400-06a5f300-8c51-11ea-9d2f-54fef8a5657c.jpg)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Browse to https://ar-js-org.github.io/AR.js/aframe/examples/marker-based/basic.html using an iOS 13 device using Safari
2. Open this picture on another machine: https://raw.githubusercontent.com/AR-js-org/AR.js/master/data/images/hiro.png
3. Use iOS device to scan marker image.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
iOS 13
Iphone Xs
Safari

**What is the expected behavior?**
I expect the dinosaur to be visible from the front and on its feet.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by tegozen** [comment]
closed....
