### ISSUE TITLE
AR.js Marker Model mobile Browser Bug Collection

### ISSUE THREAD

**Issue by EnricoBaivo** [AR-js-org/AR.js#101]
**Do you want to request a *feature* or report a *bug*?**
Maybe Bug ! My english is not perfect so please be advised

**What is the current behavior?**
1. Models are moving or shaki if the camera is straight on the marker see gif. ![ezgif-7-66d3811e4268](https://user-images.githubusercontent.com/13745823/80863314-a6787680-8c7b-11ea-91e2-c611e499ca64.gif)
2. The model and or the camera canvas(scene)  is on different mobile Devices in chrome diffrent.
For example the Huawei p30 on chrome got a "zoom" effect and the model is offset and moving with the camera movement. On Samsung s20 and ipad pro 2018 and Samsung s10 on chrome it works correckt but with the bug called above (1).

![Screenshot_20200502-120938_Samsung Internet](https://user-images.githubusercontent.com/13745823/80863404-4afab880-8c7c-11ea-835b-a6861c1c4aea.jpg)

before scene is loaded u can zoom out on the mobile browser and this results in this :
![Screenshot_20200502-120949_Samsung Internet](https://user-images.githubusercontent.com/13745823/80863414-649c0000-8c7c-11ea-912e-5bea57aa3526.jpg)

Edit: found ojt that the mobile browser setting force to zoom in(default value for: samsung internet and opera ) causes this bug, if disabled by user the camera flips back to expavted size.

3. Aspect Ratio is changing with the device movement if the Ascene is not embedded.
![ezgif-4-0f3cff7077fa](https://user-images.githubusercontent.com/13745823/80863388-2e5e8080-8c7c-11ea-9627-9c39f6bc207e.gif)

**If the current behavior is a bug, please provide the steps to reproduce.**
 Visit this page: and try it on a device like the huawei p30 or try it in the Samsung browser:
https://www.ralfmatten.de/interactive/marker.html

The shaki bug appears on every demo
**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**
1.  the model should be stay still, if the marker is aligned with the camera
2. the canvas should be always the same.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by JamesBotterill** [comment]
This from experience probable isn't the marker or ar.js but is down to the refresh rate of the monitor.

If you print it out there will be no issue.

I've only ever minimised it at best.

My settings from a project:


    smooth="true" smoothCount="10" smoothTolerance="0.02" smoothThreshold="2"
