### ISSUE TITLE
Adding a a-nft tag dynamically not working

### ISSUE THREAD

**Issue by rvigneshw** [AR-js-org/AR.js#102]
Adding a a-nft tag dynamically not working

Steps to produce:
1.Use document.createElement() to create a-nft element
2.Add the attribue values
3.Append to a-scene

But that doesn't seem to work

**Comment by nicolocarpignoli** [comment]
please provide code in order to try, follow provided template of the Issues.

**Comment by JamesBotterill** [comment]
I think that the nft tag data is loaded on page load. Is anything being logged in the console when you add it dynamically.

You might need to trigger the load manually in your script
