### ISSUE TITLE
NFT marker seems to have an offset/error in tracking

### ISSUE THREAD

**Issue by rremigius** [AR-js-org/AR.js#103]
Hi, first of all I want to say it's really great you picked up development on AR.js, and implemented image marker tracking! I got my hands dirty with it over the weekend but got stuck at marker tracking:

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Objects placed on an NFT marker are not displayed on the marker. Even in the front page T-Rex example, the T-Rex is positioned below the marker (if tracked on a vertical screen). I was unable to find the position offset that would make it appear exactly on the marker. Also tried with a small cube.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run the [T-Rex example](https://ar-js-org.github.io/AR.js/aframe/examples/marker-based/basic.html) on a phone, display the [T-Rex image](https://raw.githubusercontent.com/AR-js-org/AR.js/master/aframe/examples/image-tracking/nft/trex-image-big.jpeg) on a screen. 

Try this [codepen](https://codepen.io/rremigius/pen/QWjOmKj). It's the basic example, but with a simple box instead of a T-Rex. The box may be a bit distorted, but that's another issue, I guess.

**Please mention other relevant information such as the browser version, Operating System and Device Name**

Tested on Samsung Galaxy S10e, Android 10, Chrome 81.0.4044.117
Also on Ubuntu 18.04 Chrome 81.0.4044.122

**What is the expected behavior?**

If an object is placed on an NFT marker, with position (0,0,0), I would expect it to be displayed in the center of the marker.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
Closing because already exist see #4

**Comment by rremigius** [comment]
Right, sorry. Did see that one but didn't understand it as the same (probably because of the 'cable' title)
