### ISSUE TITLE
[location-based]: <a-camera> near and far clip planes not working as expected

### ISSUE THREAD

**Issue by nickw1** [AR-js-org/AR.js#110]
**Do you want to request a *feature* or report a *bug*?**
Possible bug.

**What is the current behavior?**
An `a-camera` is created with the far clipping plane set to 5000 WebGL units (metres), and the near plane set to 0.1 units. Objects seem to always disappear when you move around 500-1000 units away from them - no matter what the value of the far clipping plane is.

**If the current behavior is a bug, please provide the steps to reproduce.**

See example at 

https://hikar.org/webapp/test/clipPlane.html

WASD-controls are enabled so you can move around the scene. By default you look north, you can see an` a-text` 0.5km (500 units) north (towards -z) from the origin. You *should* also be able to see another `a-text `1km (1000 units) north of the origin, due to the far clipping plane value of 5000, however it only comes into view if you move 'north' for a short distance (press W).

These are simple `a-text`s with position set using the `position` attribute. The same behaviour occurs if `gps-entity-place`s with latitude and longitude are used. Also, the same behaviour occurs with either `gps-camera` or `gps-projected-camera`.

Possibly related to #52? However I do set the `logarithmicDepthBuffer` to true as suggested.

(Same behaviour occurs with polylines - roads and paths - in my Hikar webapp demo: https://hikar.org/webapp/?lat=51.049&lon=-0.723, z-flghting type flickering and polylines beyond 0.5km - 1km or so cannot be seen)

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Browser: Firefox 75.0 or Chrome 81.0 on Ubuntu 18.04 (same behaviour).

**What is the expected behavior?**
I would expect to see the `a-text` 1km north.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by nicolocarpignoli** [comment]
are you able to see them using this => https://github.com/aframevr/aframe-inspector ?

**Comment by nickw1** [comment]
Yes - they all appear in the A-frame Inspector, and are all rendered into the A-Frame Inspector scene as I would expect.

If I increase the scaling from 100 to 1000 they're visible a little further away (e.g. the 1km north entity is visible just to the south of the origin) but not much, and I still get a z-fighting type effect as they transition between being visible and invisible.

**Comment by nicolocarpignoli** [comment]
do you have added the 'look-at' custom component to each entity?

**Comment by nicolocarpignoli** [comment]
anyway, it's this very same bug I think: https://github.com/AR-js-org/AR.js/issues/30

**Comment by nickw1** [comment]
Ah, sorry, must have missed that one. Yes, it looks the same issue. Maybe it's something to do with the way the camera feed is being rendered, the camera feed is conflicting with objects some distance away?  (BTW I did add look-at).

**Comment by nickw1** [comment]
To follow up, just had a quick look through the source to try and find the webcam code -- it's triggered from ARjs.Source._initSourceWebcam() in three.js/src/threex/threex-artoolkitsource.js. This looks like it simply renders a camera feed onto the screen; it doesn't try to use WebGL to render the feed.

It looks also like an alternative approach, rendering the webcam into a WebGL texture, has been attempted but is never actually called: see ./three.js/src/threex/threex-arvideoinwebgl.js; there's an ArVideoInWebgl() method which takes a WebGL texture as a parameter. 

I am wondering if this is the way to go? In other words, stream the camera feed into a WebGL texture, draw two unprojected triangles covering the whole of the screen, and texture them using the texture containing the camera feed. This is the recommended approach in an Android OpenGL ES environment, and is the approach I've taken in my (Android) Hikar app. It works fine without any z-fighting issues or unexpected invisibility.  Not sure how easy it is to do this in JavaScript but will take a look; I'd imagine three.js might make this fairly easy to do?

**Comment by jamess922** [comment]
Hi guys 
What is the accuracy of the location-based AR could get ，like how many i need to move to see the position of image or model change？ I walk 1 meter towards the target，could i really see in the cellphone that i get 1 meter closer to the target

**Comment by nickw1** [comment]
Hi jamess922, you should be able to see a noticeable difference as you approach the target. Do bear in mind that GPS accuracy might cause issues if you're very close to a target (sometimes its accuracy is only 6m or so) but in theory it should work fine.

**Comment by nicolocarpignoli** [comment]
@nickw1 can we close this? I merged the PR on master

**Comment by nickw1** [comment]
Yes, will do!

**Comment by k7n4n5t3w4rt** [comment]
Thanks for your amazing work. I'm delighted to see that this issue I've been experiencing is fixed. Should it be available in this version now or is there a delay?

<script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>

 I'm just following the docs and I'm seeing the "<a-camera> near and far clip planes not working as expected" issue.

**Comment by WebandMobileMaster** [comment]
> do you have added the 'look-at' custom component to each entity?

What is the 'look-at' component?
Why do we need it?

**Comment by WebandMobileMaster** [comment]
https://user-images.githubusercontent.com/67555770/116979182-016a0100-ad08-11eb-8ffd-a5bf2ef68f40.mp4

If I don't use the 'look-at' component, I can not see anything.
But If I use it, the images are displayed on the floor.
Like the video.

**Comment by WebandMobileMaster** [comment]
`<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>myyaak</title>
    <link rel="shortcut icon" href="favicon.ico">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aframe/1.2.0/aframe.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/aframe-look-at-component@1.0.0/dist/aframe-look-at-component.min.js"></script>
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>

    <style>
        .a-enter-vr{
            display: none !important;
        }
    </style>
</head>

<body style="margin: 0; overflow: hidden;">
    <a-scene
        embedded
        loading-screen="enabled: false;"
        arjs="sourceType: webcam; videoTexture: true; debugUIEnabled: false;"
        inspector="https://cdn.jsdelivr.net/gh/aframevr/aframe-inspector@master/dist/aframe-inspector.min.js"
    >
            <a-image
                src="https://vr.myyaak.com/1619999825071.png"
                look-at="[gps-camera]"
                scale="1 1 1"
                gps-entity-place="latitude: -27.842074; longitude: 153.340418;"
            ></a-image>
            <a-image
                src="https://vr.myyaak.com/1619999825071.png"
                scale="1 1 1"
                gps-entity-place="latitude: -27.842083; longitude: 153.340375;"
            ></a-image>
            <a-image
                src="https://vr.myyaak.com/1619999825071.png"
                scale="1 1 1"
                gps-entity-place="latitude: -27.842055; longitude: 153.340504;"
            ></a-image>

        <a-camera gps-camera rotation-reader></a-camera>
    </a-scene>
</body>`
Here is my code.
What is wrong in here?

**Comment by WebandMobileMaster** [comment]
Should I get the altitude of the area and set it on the code?

**Comment by nicolocarpignoli** [comment]
@WebandMobileMaster the code is correct. I see that problem before on iOS and other devices. I do not know honestly the cause or the solution: but you can try to add the entities using javascript and not HTML. This is an example (in the .js file, look only for the "static" load places, not dynamic one, which is using external APIs).

The problem is with events cycle while adding entities with HTML. Instead, I got no error loading them with JS.

Anyway, It is strange as only some users face this (I do not encounter this problem with android nor ios).

**Comment by WebandMobileMaster** [comment]
Thank you for your reply, nicolo.
In Australia, is this possible?

**Comment by WebandMobileMaster** [comment]
Do you know [Ar.js studio](https://ar-js-org.github.io/studio/pages/location/index.html)? when I was going to get the sample code from it, if I select an area of Australia, the buttons are disabled.
Please try on your side. Is there any problem in Australia with the GPS?

**Comment by nicolocarpignoli** [comment]
Yes I think it is a known bug: https://github.com/AR-js-org/studio/issues/107

Have no time to look into that, maybe @nickw1 can but I think he's pretty busy with new AR.js release.

**Comment by WebandMobileMaster** [comment]
okay, Thank you.

**Comment by nickw1** [comment]
@nicolocarpignoli a little busy at the moment unfortunately, yes, so I may not have the time.
@WebandMobileMaster if you try with an `<a-box>` rather than an image does it work? And remove the look-at component?
Wondering whether there is indeed a bug with the southern hemisphere, but if you try with an `<a-box>` then you're working with the simplest possible component.

Specifically does this example work if you set `x` to your longitude and `y` to ypur latitude? If so you should see two boxes a short distance to your north.

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>GeoAR.js demo</title>
    <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
    <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>
  </head>

  <body style="margin: 0; overflow: hidden;">
    <a-scene
      vr-mode-ui="enabled: false"
      embedded
      arjs="sourceType: webcam; debugUIEnabled: false;"
    >
      <a-box 
        look-at="[gps-camera]"
		material="color: yellow"
        scale="10 10 10"
        gps-entity-place="longitude: y-0.0005; latitude: x+0.0006;"
      ></a-box>
      <a-box 
        look-at="[gps-camera]"
		material="color: red"
        scale="10 10 10"
        gps-entity-place="longitude: y-0.0001; latitude: x+0.0004;"
      ></a-box>
      <a-camera gps-camera rotation-reader> </a-camera>
    </a-scene>
  </body>
</html>
```

**Comment by nickw1** [comment]
@WebandMobileMaster note I have edited the example to fix a couple of typos, please make sure you look at the example on the issue page, not via email.

**Comment by WebandMobileMaster** [comment]
Thank you so much.
