### ISSUE TITLE
Continuously receive position and location of tracker/marker in viewport

### ISSUE THREAD

**Issue by cfcoderatcodefactory** [AR-js-org/AR.js#112]
**Do you want to request a *feature* or report a *bug*?**
Feature request:
Being able to continuously read size and position (inside viewport) of Image Tracker (or any marker).

**What is the current behavior?**
Non existing(?)
**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
To move around and resize loaded content as and when user moves camera and the tracker/marker appears in a different position – and maybe size – in the viewfinder

**Comment by meizano** [comment]
We can use registercomponent tick to receive position and rotation of an object.
Look at this code in the link [https://github.com/meizano/AR/blob/master/ar-event-marker-move.html](https://github.com/meizano/AR/blob/master/ar-event-marker-move.html)

**Comment by nicolocarpignoli** [comment]
@meizano nice stuff!
