### ISSUE TITLE
Link to get to Marker Training Docs gives error

### ISSUE THREAD

**Issue by jrDev1** [AR-js-org/AR.js#123]
Describe the bug
Clicking link to get info on Marker Training gives error
To Reproduce

Go to 'https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training'
See error
Expected behavior
Take to page with the info
Screenshots

Desktop (please complete the following information):

OS: Macbook
Browser: Safari

**Comment by nicolocarpignoli** [comment]
Please refer only to AR.js docs linked on the Readme. artoolkit.org is not managed by AR.js org and artoolkit is a dead project as far as I know (maybe you should check jsartoolkit and http://www.artoolkitx.org/)

**Comment by kalwalt** [comment]
@jrDev1 you can look at the Page https://kalwalt.github.io/artoolkit-docs/3_Marker_Training/marker_training.html   probably not the same, but this is a Copy of the old Artoolkit5 docs.
