### ISSUE TITLE
displayed content on NFT markers is not on the correct position (moves when moving or rotating the phone)

### ISSUE THREAD

**Issue by larabeer** [AR-js-org/AR.js#126]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Displayed content on NFT markers is not on the correct position (same behavior for a-image, a-box, a-entity,.....):
- the closer moving my phone to the marker, the more the displayed content moves to the  left and a little bit up. The opposite when moving the phone farther away from the marker, content moves to the right and a little bit down.
- moving my phone to the left --> content goes right. Moving my phone to the right --> content goes left.
- When rotating my phone (when changing orientation landscape/portrait as well as when rotating phone keeping the same orientation) position of displayed content moves:
-----> When rotating the phone 360 degrees, displayed object moves like on a circle line.

**If the current behavior is a bug, please provide the steps to reproduce.**
with your new iPhone SE (generation 2020) scan the trex image (with the example in aframe/examples/image-tracking/nft/index.html).

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Safari on iPhone SE (Generation 2020) with iOS 13.5.1. Didn't yet check with other phones, maybe the same behavior?

**What is the expected behavior?**
Displayed content should more or less stay on the defined position. Does anyone have an idea how to fix that? Thought about reading out the matrix/x-y-coordinates of the nft-marker in order to change the position of the displayed content, but couldn't find a way to read the NFT-marker coordinates until now... 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by weldonla** [comment]
I have the same problem on my Pixel 3 running android 10 using chrome. I even have the same behavior with the example on the [documentation page](https://ar-js-org.github.io/AR.js-Docs/ ). The object itself appears misplaced relative to the nft marker, and when moving the camera around, the object will also move around.

**Comment by kalwalt** [comment]
@larabeer  see https://github.com/AR-js-org/AR.js/issues/4 and https://github.com/AR-js-org/AR.js/pull/114
