### ISSUE TITLE
Stuck at the Loading screen sometime

### ISSUE THREAD

**Issue by jamess922** [AR-js-org/AR.js#135]
**Do you want to request a *feature* or report a *bug*?**
Maybe a bug

**What is the current behavior?**

Sometime stuck at the Loading screen and needs refresh

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Device：HUAWEI mate 20 Pro  
Operating System：Android 10
brower：Mozilla firefox

Device：Iphone 7
Operating System：IOS12.4.1
brower：Safari

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

![Screenshot_20200704_214047_org mozilla firefox](https://user-images.githubusercontent.com/28625879/86513815-ce34b800-be3f-11ea-8098-0f6f198c3371.jpg)

**Comment by yangdooo** [comment]
Why is this issue closed? Is it resolved?
