### ISSUE TITLE
Re-open discuss about smoothing over a "jittery" effect .

### ISSUE THREAD

**Issue by jamess922** [AR-js-org/AR.js#139]
**Do you want to request a *feature* or report a *bug*?**
Just re-open this issue here 

**What is the current behavior?**
[discuss about smoothing from here](https://github.com/jeromeetienne/AR.js/issues/467) 
**If the current behavior is a bug, please provide the steps to reproduce.**
With [this ar.js demo](https://github.com/AR-js-org/AR.js)，still  have a "jittery" effect .

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by jamess922** [comment]
Now even I hold the cellphone and the marker on my desk without any touch ,sitll get jittery effect

**Comment by matthewhowlandpalmer** [comment]
> Now even I hold the cellphone and the marker on my desk without any touch ,sitll get jittery effect

I am EXTREMELY EXCITED about the unbelievable potential of these scripts as well as the demos. Keep up the Amazing work Everyone. I am hoping to post some AAA QUALITY demos and examples for the git community. I also have been experimenting with demos and all demos for me are jittery difficult to explore or even hold in shot without clipping plane type issues.

**Comment by nicolocarpignoli** [comment]
Hi @jamess922 , can you please provide:

- your browser and version
- your phone and OS version
- a video of the problem

?

Thanks
