### ISSUE TITLE
simulateLongitude/Latitude/Altitude does not seem to work

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/AR.js#14]
https://github.com/jeromeetienne/AR.js/issues/752

**Comment by nicolocarpignoli** [comment]
Can't reproduce this. It actually works on my android. Steps to check:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>GeoAR.js demo</title>
    <script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
    <script src='../../../build/aframe-ar-nft.js'></script>
    <script>ARjs.Context.baseURL = '../../../../../three.js/'</script>

</head>

<body style='margin: 0; overflow: hidden;'>
    <a-scene
        vr-mode-ui="enabled: false"
		embedded
		arjs='sourceType: webcam; debugUIEnabled: false;'>

        <a-box material="color: red;" scale="15 15 15" position="0 0 0" gps-entity-place="latitude: 41.890339; longitude: 12.492586;"></a-box>
        <a-camera gps-camera="simulateLatitude: 41.890890; simulateLongitude: 12.489357;" rotation-reader>
		</a-camera>
	</a-scene>
</body>
```

Those gps camera simulate latitude/longitude are simulating your position in Rome. The red box is positioned exactly on the Colosseum. You can check those data on Google maps or similar. You can actually see the red box. 

This is one example, I have tried others and it works.

Feel free everybody to open a new issue if you see something wrong.

**Comment by marcusx2** [comment]
I really doesn't work. Not with the `gps-new-camera` at least. What happens is that if you check the position, it uses the simulated coordinates for the first frame, then it goes back to the position the user is.

```
console.log(camera.object3D.position);//correct position
setTimeout(() => {
    console.log(camera.object3D.position);//goes back to user's position
}, 0)
```

**Comment by nickw1** [comment]
@marcusx2 this will happen if you have a real GPS signal. `simulateLatitude` and `simulateLongitude` are intended for testing in situations when you do not have a GPS signal, such as a desktop/laptop environment.

**Comment by marcusx2** [comment]
`this will happen if you have a real GPS signal. simulateLatitude and simulateLongitude are intended for testing in situations when you do not have a GPS signal, such as a desktop/laptop environment.`

It happens on chrome desktop. How do I disable the gps signal to force the simulation values to take place?

**Comment by nickw1** [comment]
You should be able to turn off location tracking for your site. When you visit a site which uses location tracking, you get a prompt to turn tracking on or off. Ensure you turn it off, or turn it off later (a 'marker' or 'pushpin' icon will appear in the address bar allowing you to disable location tracking for the current website).

**Comment by marcusx2** [comment]
@nickw1 Should I make a new issue to ask for a change here? I think that if the simulate values are not 0, they should be used regardless if the gps is working or not. After all, why the extra step of having to turn off the GPS, if the simulate value already tells you if it should be used if it's different than 0? This seems unnecessary. There's also the annoyance of having to clear the cache to be asked for gps permission again, or having to use incognito mode.

**Comment by nickw1** [comment]
@marcusx2 yes, please create another issue, as this is a very old one and it's slightly different. Thanks.
