### ISSUE TITLE
Location Based gps entity altitude

### ISSUE THREAD

**Issue by FedericoLanzotti** [AR-js-org/AR.js#142]
**Do you want to request a *feature* or report a *bug*?**

Altitude Feature

**What is the expected behavior?**

Ability to add altitude as well as latitude and longitude.
In this way the pins will be displayed on the same vertical line with different height.
Eg a house at a latitude xx.xxxx and longitude yy.yyyy with a altitude of 10m (or more if it is based on sea level) will have the pin of the second floor, the same latitude and the same longitude at 13m will show the pin on the third floor.

**Comment by Theraghav** [comment]
I think we do have some control over the height of the marker using the position attribute as mentioned in 
(https://ar-js-org.github.io/AR.js-Docs/location-based/#properties)

As for gps-entity-place, you can specify an altitude using the y component of the position attribute:
`
<a-box color="yellow" gps-projected-entity-place="latitude: <your-latitude>; longitude: <your-longitude>" position="0 30 0"/>`

**Comment by nicolocarpignoli** [comment]
Yes, altitude is simulated using the y position of aframe.
