### ISSUE TITLE
Location-Based Problem with Spherical Mercator coordinates

### ISSUE THREAD

**Issue by gyc880323** [AR-js-org/AR.js#146]
**Do you want to request a *feature* or report a *bug*?**

* Feature

**What is the current behavior?**

* First of all, we're using `gps-projected-camera`, when we're moving around, the model will stay in the fixed position and it doesn't become bigger or smaller(near or far) effect.
* The model will disappear when marker lost.

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

* OS : `Android 8.0+`
* Browser : `Chrome newest`

**What is the expected behavior?**

* The behavior that we expected is making models to show the near and far effect, which means that when we come closer to the model, the model will become bigger, vice sersa.
* The model will stay at the position which locates on Spherical Mercator coordinates.

**If this is a feature request, what is motivation or use case for changing the behavior?**

* Because GPS might not be precise indoor, however, we have to locate the model in the specified position(Maybe absolute position)
* This is the effect that we want to present. In this [link](https://youtu.be/_1uJjT4bRKI), the paint is covered by the video.

**Comment by jackey10055206** [comment]
I have the same problem!

**Comment by nickw1** [comment]
Hi, I developed the gps-projected-camera and gps-projected-entity-place components. @gyc880323 @jackey10055206 do you have source code which I can test, or can you give me source code snippets here? Thanks.

**Comment by jackey10055206** [comment]
@nickw1 Thanks for replying to this issue, and @gyc880323 and I are members of the same project!
By the meantime, we are still testing the demo code which directory is [https://github.com/AR-js-org/AR.js/blob/master/aframe/examples/location-based/projected-base-camera/basic/index.html](https://github.com/AR-js-org/AR.js/blob/master/aframe/examples/location-based/projected-base-camera/basic/index.html)

In this demo, the distance between my camera and models is fixed.
But the effect that we want is that the model's scale will be changed when we get closer to the model or get farther.

We have two opinions now.

1st. When we scan the marker, my camera is in the position (0,0,0) in Spherical Mercator, is that possible that I can move my camera but not to change my original position (0,0,0), so in the Spherical Mercator, my camera is the only dot that can move.

2nd. When we scan the marker, my camera is in the position (0,0,0) in Spherical Mercator. Now, if I move forward for one meter, the model which is on the relative position can be bigger?
We want to calculate the distance that the camera move so we can change the model's scale, which can make it has an effect that we do get closer to the model, but in fact, we don't. The distance between the camera and the model doesn't change.

I don't know whether it is possible.

**Comment by nickw1** [comment]
Hi @jackey10055206 so you want to be able to set the camera in Spherical Mercator relative to the origin, whereas at the moment you can only change the position by setting the latitude and longitude? It is kind-of possible to do this at the moment but a bit messy. Let me add an additiional API call to be able to do this cleanly. This shoudn't take long; I am likely to be able to do this tomorrow.

The demo currently uses a fixed latitude and longitude (using `simulateLatitude` and `simulateLongitude`); that's why you don't appear to be able to move.

**Comment by jackey10055206** [comment]
Hey, @nickw1 Thanks for replying to my question!
Let me describe my first opinion
* When I scan the marker, my camera is on the origin position (0,0,0), let's called it `PointA`.
* In the Spherical Mercator, my model is in somewhere which is `PointB`
* So now, `PointA` and `PointB` are fixed.
* My camera, which is PointC. It was on `PointA` at first, as soon as `PointA` and PointB are fixed, I want to move my camera!
* In this Spherical Mercator, the only point that can move is `PointC`, `PointA` and `PointB` are fixed points in the Spherical Mercator.
* When `PointA` and `PointB` are fixed, my `PointC`(my camera) move forward to `PointB`(model), the model will get bigger!
* That's the effect I am working on

And I was wondering that the only way to change the position in Spherical Mercator is setting the latitude and longitude?  Is there another way to do that?  Cause we thought that GPS might not be so precisely indoor. Again, thanks for replying to my question!

**Comment by nickw1** [comment]
Hi @jackey10055206 thinking about this, and looking at the code, I'm not sure that `gps-projected-camera` is the best place to put this, as it's very much focused on translating GPS coordinates to Spherical Mercator. 

You don't need a Spherical Mercator projection as such, you just need to work with native A-Frame/WebGL coordinates and map one coordinate unit to one metre

Just using plain A-Frame, you can set the `position`property of the `a-camera` e.g. 
```javascript
const camera = document.querySelector('a-camera');
camera.setAttribute('position', { x: ..., y: ..., z: ... });
```
Are you using changes in the size of the marker to calculate changes in position? (I'm not so familiar with the marker-based API). Once you have worked out how far you've moved, you can then adjust the camera position using the code above.

To set the position of your model initially, you'd just use the standard A-Frame `position` property eg
``` html
<a-box position='x y z'>
```

or in JavaScript:
```
boxEl.setAttribute('position', { x: ..., y: ... , z: ... });
```
Does that help, or is there something else you need? As I said, I am not familiar with the marker-based part of the API.

**Comment by jackey10055206** [comment]
Hi, @nickw1.  Thanks for replying to my question!
I'll try the solutions that you suggested, I am still new to AR.js, and maybe my thoughts were wrong!
Anyway, I think your suggestion is really helpful!
Thanks for helping me!
