### ISSUE TITLE
Mouse click handle in AR.js

### ISSUE THREAD

**Issue by jackey10055206** [AR-js-org/AR.js#148]
**Do you want to request a *feature* or report a *bug*?**

* Bug

**What is the current behavior?**

* The [aritcle](https://medium.com/chialab-open-source/how-to-handle-click-events-on-ar-js-58fcacb77c4) which is written by @nicolocarpignoli is using aframe `v0.9.0`, but it has some error logs.
* We are using `v0.8.0` that it can work perfectly.
* At aframe `v1.0.x`, the mouse click cannot work.
* **I remove `embedded` on `<a-scene>`, It will work perfectly even in `v1.0.x`**
    But if I didn't add `embedded`, the model will be stretched.

**If the current behavior is a bug, please provide the steps to reproduce.**

* Changing aframe version to `1.0.x`
* And I notice that if I added `embedded` on `<a-scene>`, it will not work

**Please mention other relevant information such as the browser version, Operating System and Device Name**

* OS : `Android 8.0+``
* Browser : `Chrome newest`

**What is the expected behavior?**

* The behavior that I want is that I can run it on `v1.0.x`
* I want to add `embdded` in my code, and it can run perfectly.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by gyc880323** [comment]
I have the same problem!

**Comment by knightMash** [comment]
+1

**Comment by navanchauhan** [comment]
@jackey10055206  can you provide us with a minimal code sample?

**Comment by jackey10055206** [comment]
Hi @navanchauhan ! Thanks for replying to this issue! I've already solved the problem!
Thanks for your help!!

**Comment by navanchauhan** [comment]
@jackey10055206 Awesome! If you want can you please post how you solved it and then close the issue. 

Happy Tinkering!
