### ISSUE TITLE
Position update bug

### ISSUE THREAD

**Issue by FedericoLanzotti** [AR-js-org/AR.js#150]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the position of the pins is updated, the pins themselves move from right to left.
Is it a solvable problem? or does it depend on the accuracy of the position?

**Comment by JamesBotterill** [comment]
This is because your device hasn't locked your true position at the location, it's the same reason your position with jump when in maps. 

Until accuracy on the device improves drastically this isn't something the lib can resolve.

**Comment by FedericoLanzotti** [comment]
> This is because your device hasn't locked your true position at the location, it's the same reason your position with jump when in maps.
> 
> Until accuracy on the device improves drastically this isn't something the lib can resolve.

Thanks.

Is there a way to always establish the real position? Or a way to manage the launch time of the update-position event?

**Comment by nicolocarpignoli** [comment]
We have added properties for this. Smooth distant places position and near places.
Will have to make the docs yet. 
But you can check on `gps-camera` code latest properties => use them with version 3.3.1 

https://github.com/AR-js-org/AR.js/blob/master/aframe/src/location-based/gps-camera.js

Check next days on the official AR.js docs for these new properties documentation  and how to use them.
