### ISSUE TITLE
Move alert from camera-error customEvent

### ISSUE THREAD

**Issue by leoz2007** [AR-js-org/AR.js#152]
⚠️ Important: please check the old AR.js repository's issues: https://github.com/jeromeetienne/AR.js/issues probably your question had been already answered there ⚠️
 **=>** **I see this issue on the old repo https://github.com/jeromeetienne/AR.js/issues/672**

**feature** / **bug**
We can't catch the customEvent Camera-error before the default Alert

**What is the current behavior?**
The default alert are displayed before fired camera-error event
https://github.com/jeromeetienne/AR.js/blob/08a720e359a18ba7bf6cac6077c3d9472aa40d28/three.js/src/threex/threex-artoolkitsource.js#L164

**What is the expected behavior?**
Be able to catch the event before displaying the default alert. 
Right now I catch the event through 
```
window.addEventListener(
        "camera-error",
        function(e) {
          console.log("FREEEEEEED =>", e);
        },
        false
      );
```

The only way I found to display my console.log is to click ok on the default alert.

Maybe we can move the alert after the dispatchEvent, like that:
```
onError = onError || function(error){
		var event = new CustomEvent('camera-error', {error: error});
		window.dispatchEvent(event);
		alert('Webcam Error\nName: '+error.name + '\nMessage: '+error.message)
	}
```

**Comment by nicolocarpignoli** [comment]
easy fix but important one. Just made it on master branch. It's available with v3.2.1
thanks!
