### ISSUE TITLE
Not able to show video after adding my own marker

### ISSUE THREAD

**Issue by ramanprtap** [AR-js-org/AR.js#154]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
its not detecting the marker just stuck on "Loading, Please wait..."

**If the current behavior is a bug, please provide the steps to reproduce.**
bug

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Android
**What is the expected behavior?**
It should detect the marker and play the video

images set 
https://github.com/ramanprtap/AR-JS/tree/master/hres/1.[ext]

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by nicolocarpignoli** [comment]
Please re-open the issue adding your code, your device specs and os specs (also browser).
