### ISSUE TITLE
Slam / Markerless AR

### ISSUE THREAD

**Issue by ourbuziness** [AR-js-org/AR.js#155]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
not supported
**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
Today Slam or markless ar is a Must for an AR framework

I have reviewed many issues or feature requests , and followed your progress on documenting and adding slam feature in your trello . but no where found any solutions for this .
Is this feature ( slam ) or markerless tracking developed and usable in AR.js ?

thank you very much for your supporting

**Comment by nicolocarpignoli** [comment]
Hi,
it is not supported at the moment. No plans for the future, we are focusing on making better the location, marker and image tracking. 

>Today Slam or markless ar is a Must for an AR framework

Well, it depends on use cases :)
You can use AR.js in conjunction with other frameworks libraries that offer that: check WebXR and ModelViewer.
