### ISSUE TITLE
Is it possible to place a function call intead of an object?

### ISSUE THREAD

**Issue by Wolgraph** [AR-js-org/AR.js#157]
I'm trying to develop an AR app where the objects are placed procedurally depending on what marker is recognized.
Is it possible to "spawn" a call to the function which will create and place the objects in the scene?

**Comment by nicolocarpignoli** [comment]
Yes. You can use native Javascript APIs like 'createHTMLElement', 'setAttribute' and 'appendChild' in order to add stuff to the DOM(like markers).

check this  out: https://aframe.io/docs/1.0.0/introduction/javascript-events-dom-apis.html
