### ISSUE TITLE
GLTF model rendering incorrectly with NFT marker

### ISSUE THREAD

**Issue by juanapp** [AR-js-org/AR.js#158]
Hi all,

I'm currently working on a project where we use NFT markers to place our 3D models. Those 3D models are working correctly with the typical Hiro marker but when using NFT, the model renders quite weirdly.
For example, the further you get, the least layers of the model you see and whenever you get closer, layers(textures) start to show up, which makes it quite useless at this moment for our implementation.

I believe this is a bug, since it's not happening with standard markers or different 3D viewers.

Example images:
[https://i.stack.imgur.com/cDRk2.jpg](url)
[https://i.stack.imgur.com/A1FpE.jpg](url)

**Comment by juanapp** [comment]
This is still the case. Anybody has an idea on what can be the cause?

**Comment by bonisaputra** [comment]
use this
`renderer="logarithmicDepthBuffer: true;"`

inside your <a-scene> attribute
