### ISSUE TITLE
Location based AR: simulate altitude separately 

### ISSUE THREAD

**Issue by NVFedorov** [AR-js-org/AR.js#167]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently there is no way to separately simulate altitude and use the original latitude and longitude. The altitude is no being taken into account only of the Y position of an entity is 0 which is not always the case.

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**
When I set ```simulateAltitude``` (as per https://ar-js-org.github.io/AR.js-Docs/location-based/#properties) I expect that all the calculations are being made relatively to this simulated altitude. In particular here: https://github.com/AR-js-org/AR.js/blob/11d3225c5e821df46a91f458f80de839f7944c82/aframe/src/location-based/gps-entity-place.js#L105

**If this is a feature request, what is motivation or use case for changing the behavior?**
The altitude determination is really inaccurate process, it depends on satellite positions relatively to horizon and is not accurate in center of a city with tall buildings.

**Comment by nicolocarpignoli** [comment]
I agree. Are you able to provide a PR?

I think these are the point where to modify (actually, as you said, we are using the simulateAltitude only if simulateLat/Long are set. So it's not possible to simulateAltitude alone).

https://github.com/AR-js-org/AR.js/blob/master/aframe/src/location-based/gps-camera.js#L38

https://github.com/AR-js-org/AR.js/blob/master/aframe/src/location-based/gps-camera.js#L101

**Comment by NVFedorov** [comment]
I copied the build and tried to add altitude simulation, but the Y position is still being calculated using actual altitude. Not sure what's wrong, it should be as simple as:

```
this._watchPositionId = this._initWatchGPS(function (position) {
            if (this.data.simulateLatitude !== 0 && this.data.simulateLongitude !== 0) {
                localPosition = Object.assign({}, position.coords);
                localPosition.longitude = this.data.simulateLongitude;
                localPosition.latitude = this.data.simulateLatitude;
                localPosition.altitude = this.data.simulateAltitude;
                this.currentCoords = localPosition;
            }
            else {
                this.currentCoords = position.coords;
                if (this.data.simulateAltitude !== 0) {
                    this.currentCoords.altitude = this.data.simulateAltitude;
                }
            }

            this._updatePosition();
        }.bind(this));
```

The currentCoords get changed, but the calculations are not...

**Comment by nicolocarpignoli** [comment]
That way it will work only  if simulateLatitude and simulateLongitude are not set. It's better the handle each of them separately. 

Anyway, you should modify also on another point of the  code. Look on my previous post, there are two different places on gps-camera that should be changed in order to make it work.

**Comment by NVFedorov** [comment]
this one works:
https://glitch.com/~kindly-verbena-loan

but there is a strange thing: 
in glitch ```Object.assign({}, position.coords);``` doesn't work (simply doesn't assign properties of position.coords. Locally works fine. Don't know what kind of magic is this.

Do I have to build sources for PR? I'm not really familiar with makefiles, tried to build on windows, but for some reason the file sizes are different. (I'm using nmake and type instead of cat)

**Comment by nicolocarpignoli** [comment]
No problem for the builded files, for the PR we just need the modified sources.
