### ISSUE TITLE
gps-camera and gps-projected-camera components add event listener and don't remove it on component removal

### ISSUE THREAD

**Issue by NVFedorov** [AR-js-org/AR.js#172]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The 'gps-entity-place-added' event get's handled even after gps-camera/gps-projected-camera removal.

**If the current behavior is a bug, please provide the steps to reproduce.**
When you add gps-camera (or gps-projected-camera) components, they add event listener: https://github.com/AR-js-org/AR.js/blob/11d3225c5e821df46a91f458f80de839f7944c82/aframe/src/location-based/gps-camera.js#L59

When you remove the component event listener doesn't get removed.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
any

**What is the expected behavior?**
Event listener gets removed after component is removed
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by nickw1** [comment]
@NVFedorov This is also I believe fixed; feel free to check last commit on dev.

**Comment by NVFedorov** [comment]
@nickw1, it works like a charm, thank you!

**Comment by nickw1** [comment]
@NVFedorov no problem!
