### ISSUE TITLE
gps-camera doesn't do 'clearWatch' on aframe pause event.

### ISSUE THREAD

**Issue by NVFedorov** [AR-js-org/AR.js#174]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
gps-camera doesn't stop watch position when aframe scene pause event is being called.
**If the current behavior is a bug, please provide the steps to reproduce.**
1.Create a basic ar.js with aframe scene, 
2. Call scene.pause(),
3. GPS position is still being watched.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
any
**What is the expected behavior?**
```navigator.geolocation.clearWatch(this._watchPositionId);``` should be called. On scene.play() ```this._watchPositionId = this._initWatchGPS(/** **/) ``` should be called.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by nickw1** [comment]
Will fix this, likely tomorrow or the weekend.

**Comment by nickw1** [comment]
@NVFedorov ok now fixed on dev. Will close.

**Comment by NVFedorov** [comment]
Thank you!

**Comment by nickw1** [comment]
No problem!
