### ISSUE TITLE
NFT Video example does not play video

### ISSUE THREAD

**Issue by Epiczzor** [AR-js-org/AR.js#175]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The Video plane loads on the marker but does not play

**If the current behavior is a bug, please provide the steps to reproduce.**
Visit the live example for Video NFT here : https://ar-js-org.github.io/AR.js/aframe/examples/image-tracking/nft-video/

**Please mention other relevant information such as the browser version, Operating System and Device Name**
iPhone X on Safari

**What is the expected behavior?**
It should autoplay the video

**If this is a feature request, what is motivation or use case for changing the behavior?**
```

The code below that is supposed to handle the Playing and Pausing of the video never executes
AFRAME.registerComponent('videohandler', {
              init: function () {
                var marker = this.el;
                this.vid = document.querySelector("#vid");
                marker.addEventListener('markerFound', function () {
                  this.vid.play();
              }.bind(this));
      
              marker.addEventListener('markerLost', function() {
                this.vid.pause();
                this.vid.currentTime = 0;
              }.bind(this));
                      }
            });
```

**Comment by Epiczzor** [comment]
Okay, I managed to resolve this, must add "videohandler" in a-nft tag as below
```
<a-nft
          videohandler
          type="nft"
....
```

**Comment by nicolocarpignoli** [comment]
What you mean with 'it is not working' ? 
Please open an issue with a specific bug if found. The previous one is solved, that's great.
