### ISSUE TITLE
Click event on an a-entity inside a marker isn't fired

### ISSUE THREAD

**Issue by vittore** [AR-js-org/AR.js#182]
**Do you want to request a *feature* or report a *bug*?**
- Bug

**What is the current behavior?**
- Click event is not fired. 

**If the current behavior is a bug, please provide the steps to reproduce.**

I have a simple code where there is a plane over barcode marker, when I click on this plane this action toggle visibility to another entity.

```
<!doctype HTML>
<html>
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
</head>
<script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
<script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></script>
</head>
<body style='margin : 0px; overflow: hidden;'>
<script>
    AFRAME.registerComponent("markerhandler", {
        init: function () {
            const animatedMarker = document.querySelector("#animated-marker");
            var toggle= false;
            animatedMarker.addEventListener('click', function (ev, target) {
                console.log('click event on #animated-marker fired')
                toggle=-toggle;
                const element = document.querySelector("#show-hide-entity");
                element.setAttribute('visible',toggle);
            })
        }
    })
</script>
<a-scene embedded
         arjs='sourceType: webcam; debugUIEnabled: false; detectionMode: mono_and_matrix;  matrixCodeType: 4x4_BCH_13_9_3;'>



    <a-marker type='barcode' value='1' emitevents="true" markerhandler>
        <a-entity cursor="rayOrigin: mouse" raycaster="objects: .clickable; useWorldCoordinates: true;"></a-entity>
        <a-entity geometry="primitive: plane; width: 1; height: 1"
                  material="color: red;  opacity:0.7; side: double"
                  text="value: click me; align: center; wrapCount: 15"
                  position="0 0 0"
                  rotation="-90 0 0" class="clickable"
                  id="animated-marker"></a-entity>
        <a-entity geometry="primitive: plane; width: 1; height: 1"
                  material="color: blue;  opacity:0.7; side: double"
                  text="value: All it's ok; align: center; wrapCount: 15"
                  position="1 0 0"
                  rotation="-90 0 0"
                  id="show-hide-entity" visible="false"></a-entity>
    </a-marker>
    <a-entity camera></a-entity>
</a-scene>
</body
</html>
```

Code ```console.log('click event on #animated-marker fired')``` don't run when red plane is clicked.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
- Same as #148 
- Documented in stackoverflow: https://stackoverflow.com/questions/63151052/click-event-on-a-entity-in-ar-js

Used references and documentation:

[How to handle click events on AR.js](https://medium.com/chialab-open-source/how-to-handle-click-events-on-ar-js-58fcacb77c4)
[Event listeners in ar.js](https://stackoverflow.com/questions/60935284/event-listeners-in-ar-js)
[OnClick on model in AFrame-AR.js scene](https://stackoverflow.com/questions/52925132/onclick-on-model-in-aframe-ar-js-scene)

**What is the expected behavior?**
- When I click on this plane this action toggle visibility to another entity.

If I change to
```<script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>```
all code is working fine.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by dzoech** [comment]
I experienced the same problem that no events are emitted.

```
<script>
    var box = document.querySelector('#my-box-within-a-marker');
    box.addEventListener('isPlaying', function () { console.log("isPlaying")} );
    box.addEventListener('hasLoaded', function () { console.log("hasLoaded")} );
    box.addEventListener('click', function () { console.log("click")} );
</script>
```
Not any of these listeners are triggered (or at least I don't see any logs.

**Comment by Yaugan** [comment]
I also encountered the same issue but in my case the clicks are triggered but not in the right spots. Like there is a sphere and cube in my scene and I am able not able to click on the middle sphere but I am able to click on the edge of it and it will run then

**Comment by nicolocarpignoli** [comment]
duplicate: https://github.com/AR-js-org/AR.js/issues/66
