### ISSUE TITLE
ipad pro issue

### ISSUE THREAD

**Issue by venice-and-death** [AR-js-org/AR.js#184]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
It is simply not working on an Ipad pro with ios13.7 but it will work on other ios devices
**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by nicolocarpignoli** [comment]
Please detail more. What is not working? Provide a link or at least the code.
