### ISSUE TITLE
a-nft URL no found Error in loading marker on Worker 404

### ISSUE THREAD

**Issue by Rodrigosik** [AR-js-org/AR.js#185]
Good morning everyone, I have a problem that I have been looking for and I cannot find any solution
It's about the URL attribute
url='https://rutadeldominio.com/src/marker/palomitas_ntf/palomitas'
for example when I do this it does not work for me it says that it cannot find the images nft 404

<a-nft
      type="nft"
      url='https://rutadeldominio.com/src/marker/palomitas_ntf/palomitas'
      smooth="true"
      smoothCount="10"
      smoothTolerance=".01"
      smoothThreshold="5"
    >
          <a-image src="https://natrium83.github.io/arbild/assets/bild.png"
              scale="5 5 5"
              position="150 -150 -150"
              crossorigin
              height='100' width='100'
          >

    </a-nft>

Error in loading marker on Worker 404
the path of this is just an example https://rutadeldominio.com/src/marker/palomitas_ntf/palomitas

**Comment by nicolocarpignoli** [comment]
please provide full code and follow the template provided on the issue

**Comment by Rodrigosik** [comment]
`<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Web AR</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  
  <script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@1c2407b26c61958baa93967b5412487cd94b290b/dist/aframe-master.min.js"></script>
  <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>
  <script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>

  
  <link rel="stylesheet" href="css/animations.css">
 
  
  <link rel="stylesheet" type="text/css" href="css/style.css">


</head>

<body>

  <div class="arjs-loader">
    <div>Loading, please wait...</div>
  </div>

  <img src="src/imagenes/efecto1.gif" id="imagenEfectos">

  <div id="ContenedorBotones">
    <button class="btn btn-outline-warning mr-3" id="acc_Correr">Correr</button>
    <button class="btn btn-outline-warning" id="acc_Bailar">Bailar</button>
    <button class="btn btn-outline-warning ml-3" id="acc_Saludar">Saludar</button>
  </div>

  <a-scene 
    vr-mode-ui="enabled: false;"
    renderer="logarithmicDepthBuffer: true;"
    embedded
    arjs="trackingMethod: best; sourceType: webcam;debugUIEnabled: false;" 
    id="Ecena3D">

    <a-nft
      type="nft"
      url='https://demo-augmented.onepeoplecloud.com/Demo/src/marker/palomitas_ntf/palomitas'
      smooth="true"
      smoothCount="10"
      smoothTolerance=".01"
      smoothThreshold="5"
    >
          

          <a-entity gltf-model="url(src/Objetos3D/Roboto.glb)" animation-mixer="clip: Dance" scale="50 50 50"
        rotation="-90 0 0" id="modelo3D" height='100' width='100'>
          </a-entity>

    </a-nft>


    <a-entity camera></a-entity>


  </a-scene>


  
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>

  
  <script src="js/main2.js">

  </script>

</body>

</html>`

**Comment by Rodrigosik** [comment]
`<a-scene 
    vr-mode-ui="enabled: false;"
    renderer="logarithmicDepthBuffer: true;"
    embedded
    arjs="trackingMethod: best; sourceType: webcam;debugUIEnabled: false;" 
    id="Ecena3D">

    <a-nft
      type="nft"
      url='https://demo-augmented.onepeoplecloud.com/Demo/src/marker/palomitas_ntf/palomitas'
      smooth="true"
      smoothCount="10"
      smoothTolerance=".01"
      smoothThreshold="5"
    >
          

          <a-entity gltf-model="url(src/Objetos3D/Roboto.glb)" animation-mixer="clip: Dance" scale="50 50 50"
        rotation="-90 0 0" id="modelo3D" height='100' width='100'>
          </a-entity>

    </a-nft>


    <a-entity camera></a-entity>


  </a-scene>`

**Comment by nicolocarpignoli** [comment]
It is impossible to tell the problem. We need to know where your resources are (so the check if paths are correct). Also, the paths may be all corrects but you may have choose poor recognisible images for the tracking.
Please open a new issue with the full code (better a link to the whole github repository where the code is hosted). Also a Github pages link for a live example will speed up the test for us.
