### ISSUE TITLE
depth sensing and environmental occlusion possible with AR.js ?

### ISSUE THREAD

**Issue by dataexcess** [AR-js-org/AR.js#202]
Hi,

I would like to make a web AR project that would achieve the following:
https://www.youtube.com/watch?v=8fs0MMJhKVU&ab_channel=Prof.TomokiItamiya%27sLaboratory

I am considering using AR.js but want to know if aht you see in the video is feasible with AR-js. (depth-sensing, environmental/surface occlusion, etc.)

Thank you!

**Comment by ThomasRutzer** [comment]
Hi, unfortunately, this should not be possible with AR.js or web-based technologies at all (yet). But there are specifications for an [upcoming WebXR feature ](https://github.com/immersive-web/depth-sensing/blob/main/explainer.md)that may help you. Keep in mind that this is highly experimental for now. [This video](https://twitter.com/mrmaxm/status/1329151944540254208) might be interesting for you as well.

**Comment by dataexcess** [comment]
@ThomasRutzer thank you for the quick answer. This was indeed what I came to the conclusion of. For our project we need availability on both iOS and Android devices and possible also web.

As the webXR feature only works on Android Chrome, I will use Unity AR Foundation and build to both iOS and Unity, then make a website which deep-links to the native apps whenever we would present AR content.

Looking forward to be able to do everything in the browser though and to use AR.js. Thank you for your help!

**Comment by ThomasRutzer** [comment]
@dataexcess you might close this issue?
