### ISSUE TITLE
Simple way to get the distance from camera to marker

### ISSUE THREAD

**Issue by diskgrinder** [AR-js-org/AR.js#207]
Feature request: simple way to get position, orientation, distance of marker. Where is this data? 

There doesn’t appear to be a simple way to get distance from the camera to the marker.

I have found how to get the position from the Arcontroller. This object also includes line and vertex which aren’t documented clearly.

**Comment by nicolocarpignoli** [comment]
https://github.com/AR-js-org/AR.js-Docs/blob/master/docs/ui-events.md#get-distance-from-marker
