### ISSUE TITLE
threejs v ersion don't have "markerLost" event?

### ISSUE THREAD

**Issue by Hocti** [AR-js-org/AR.js#210]
I searched the source code, only aframe has both "markerFound" "markerLost" event, 
threejs version only has "markerFound"

**Comment by ThomasRutzer** [comment]
Hi, yes this is really an issue, bc this event is often needed. Looking at the src, I think the event should be fired here: https://github.com/AR-js-org/AR.js/blob/master/three.js/src/threex/threex-armarkercontrols.js#L247

maybe some more experienced developer of AR.js could help out…

**Comment by nicolocarpignoli** [comment]
We have merged this on dev branch. Point to dev branch if you need this feature before the next release.
