### ISSUE TITLE
Nft pattern creation is slow with nodejs marker creator but fast with web marker creator

### ISSUE THREAD

**Issue by ezegyfa2** [AR-js-org/AR.js#214]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If I try to create a marker from a 2000x2000 hiro image it takes 10min with nodejs version (https://github.com/Carnaux/NFT-Marker-Creator) but only a few second with web version (https://carnaux.github.io/NFT-Marker-Creator/)

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a 2000x2000 image from hiro and use the creators.

**Please mention other relevant information such as the browser version, Operating System and Device Name**

windows 10, google chrome, the nodejs version tried in linux

**What is the expected behavior?**

The nodejs marker creator creates marker fast like the web version.

**Comment by kalwalt** [comment]
Hi @ezegyfa2 even if Ar.js use NFT tech, The question regard NFT-MarkerCreator not AR.js itself. please open an issue on https://github.com/Carnaux/NFT-Marker-Creator.
