### ISSUE TITLE
click events on 3D model

### ISSUE THREAD

**Issue by williamqian** [AR-js-org/AR.js#216]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
click event is not fired on 3D model

**If the current behavior is a bug, please provide the steps to reproduce.**
I want to listen the click event on the box by mouse click directly on it
if I import aframe only，the example works well:
[aframe 3D click](https://codepen.io/williamqian/pen/ExNjZgO)

but after I import the ar.js，it doesn't work:
[aframe+ar.js 3D click](https://codepen.io/williamqian/pen/VwmLPrL)

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by williamqian** [comment]
Can someone help me？

**Comment by halfmonty** [comment]
I don't know why but the latest version of AFrame that clicking works with Ar.Js is 0.9.2 . So I'd recommend you try updating your aframe script reference to that older version and trying again, like:  https://aframe.io/releases/0.9.2/aframe.min.js

**Comment by williamqian** [comment]
> I don't know why but the latest version of AFrame that clicking works with Ar.Js is 0.9.2 . So I'd recommend you try updating your aframe script reference to that older version and trying again, like: https://aframe.io/releases/0.9.2/aframe.min.js

thanks, it works somewhat，not so accurate

**Comment by nickw1** [comment]
Hi @williamqian does this work for you?

https://hikar.org/webapp/ex1.html

It shows a red box, *not* a model, but click events definitely work and it should be the same principle.
It uses A-Frame 1.0.4.

Try that with 1.0.4+ and see if that works, I have a feeling the way you set the `raycaster` has changed recently. You need to set the near and far parameters of the `raycaster` component of your `<a-scene>`.

**Comment by williamqian** [comment]
> Hi @williamqian does this work for you?
> 
> https://hikar.org/webapp/ex1.html
> 
> It shows a red box, _not_ a model, but click events definitely work and it should be the same principle.
> It uses A-Frame 1.0.4.
> 
> Try that with 1.0.4+ and see if that works, I have a feeling the way you set the `raycaster` has changed recently. You need to set the near and far parameters of the `raycaster` component of your `<a-scene>`.

I wonder why your's works perfect，may I have your source code please?

**Comment by williamqian** [comment]
> @williamqian It's all in the HTML page, so you just need to view the source of the URL I gave you.

thank you very much，it works perfect in pc，but in mobile the picture is elongated，so I use halfmonty's solution at last.

**Comment by nicolocarpignoli** [comment]
We have to dig deeper about this. As for now, a-frame 0.9.2 makes clicks on models work.
With "work" I mean that the clicks are reliable on the center of the screen, not so much in corners. So you probably can use this if you have only one 3D model/content at a time, not many.

Sorry but we need to understand this but time is poor, at least for me.
If you need to manipulate the object (like rotating it) you can attach gestures to the entire window, the effect is very nice: see https://medium.com/@fabiojcortes/manipulate-your-3d-content-with-gestures-in-ar-js-78da4c076607

**Comment by nicolocarpignoli** [comment]
duplicate: https://github.com/AR-js-org/AR.js/issues/66
