### ISSUE TITLE
Marker based and NFT not working anymore

### ISSUE THREAD

**Issue by max-koa** [AR-js-org/AR.js#222]
**Do you want to request a *feature* or report a *bug*?**
Possible bug

**What is the current behavior?**
Marker Based tracking and NFT not working. They only work with the default markers (hiro and kanji).

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a marker or a nft image. Using them won't do anything. But if you point to a Hiro marker the model/shader/image will appear.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Using Chrome Versión 88.0.4324.150 (Build oficial) (64 bits).
Also tested in android phone also using chrome.

**What is the expected behavior?**
It is expected to display the image or shader with the provided marker.

**If this is a feature request, what is motivation or use case for changing the behavior?**
no.

I would like to add that it was working perfectly a few months ago. I was not able to touch this project for a while. And now they simply don't work anymore, which would remove the theory of 'bad image for marker'. The only change I've done is the version from cdn.

Also I would like to mention that SOME are working with the Hiro marker, but they are weirdly positioned. For example, I have one set for a specific Marker. It is not working with this Marker. But if I use the Hiro marker, the <a-plane> appears, but it is positioned like 90 degrees, which is not something I have set. Also in another case, it is positioned with a rotation of maybe 30 degrees or so, also with the Hiro marker. Basically, Hiro works almost always with weird positioning, while I have not set it to react with the hiro marker, but with other markers.

If I am doing something wrong or more information is required, please let me know.

**Comment by navanchauhan** [comment]
Can you show your code

**Comment by joshua3D** [comment]
I have gotten the web console to 'respond' to an nft I created, using the script for three.js + ar-nft.js, but only if I include a camera_para.dat for the artoolkit context controller like so:

```
    // create atToolkitContext
    arToolkitContext = new THREEx.ArToolkitContext({
        cameraParametersUrl: '/data/camera/camera_para.dat',
        detectionMode: 'mono',
        canvasWidth: 480,
        canvasHeight: 640,
    }, {
        sourceWidth: 480,
        sourceHeight: 640,
    });
```

this is how it is set up in the repos, which does not work for me

```
    // create atToolkitContext
    arToolkitContext = new THREEx.ArToolkitContext({
        detectionMode: 'mono',
        canvasWidth: 480,
        canvasHeight: 640,
    }, {
        sourceWidth: 480,
        sourceHeight: 640,
    });
```

and even then, the only 'response' I get is through the web console. I can't get any actual AR content to appear. I've only had success with the markers for that much, so far.

**Comment by nicolocarpignoli** [comment]
Provide your full code on a runnable environment, like codepen. Also, try to start from examples on the AR.js Docs homepage.
