### ISSUE TITLE
Not able to go towards the 3D model or rotate around it

### ISSUE THREAD

**Issue by gabriele-lorusso** [AR-js-org/AR.js#224]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
the object seems blocked in space (as it should) but I am not able to go towards it, or rotate around it

**If the current behavior is a bug, please provide the steps to reproduce.**
this is the link of my github of the code:
https://github.com/gabriele-lorusso/AV_AR_test/blob/main/index.html
this is the github pages: 
https://gabriele-lorusso.github.io/AV_AR_test/

**Please mention other relevant information such as the browser version, Operating System and Device Name**
I am testing it on a One plus 6, with Chrome

**What is the expected behavior?**
I thought I could achieve something similar to Sketchfab AR (without the controls over the scale and rotation of the object from the user side) ,with the difference of not placing the model yourself but just having it pop when on location

**If this is a feature request, what is motivation or use case for changing the behavior?**
even though this is not a feature request I wonder if the location could be use just as a trigger so once the model is present it can be examined

Thank you in advance for any feedback

**Comment by nickw1** [comment]
Hi Gabriele, are you using this with a mobile device and physically moving towards the AR object, and finding that the AR object stays at the same location relative to you (e.g. always 5 metres in front of you) rather than always in the same real-world (lat/lon) location?

Is this the sample code completely unchanged (except for your latitude and longitude)?

**Comment by gabriele-lorusso** [comment]
Hi @nickw1 , yes that is exactly the kind of issue that I have.

the sample code that I found in an article from Nicolò Caripignoli is slightly different but also with that one I hade the same issue. I changed the head as some I think the scripts in the original one have been updated. Here the original head from the article:
`<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>GeoAR.js demo</title>
    <script src='https://aframe.io/releases/0.9.2/aframe.min.js'></script>
    <script src="https://raw.githack.com/jeromeetienne/AR.js/master/aframe/build/aframe-ar.min.js"></script>
    <script src="https://raw.githack.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
    <script>
        THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/jeromeetienne/ar.js/master/three.js/'
    </script>
</head>`

**Comment by nickw1** [comment]
Hi @gabriele-lorusso try the "Basic example" here:
https://ar-js-org.github.io/AR.js-Docs/location-based-tutorial/

You can use the exact <script> links shown on the code. (The ones you mention above are for an old version of AR.js so you were correct to update).

Does that one work? I know it works for me; if it doesn't it may be an issue with your hardware.

**Comment by gabriele-lorusso** [comment]
Hi @nickw1 thanks for the reply. I've tried the basic example as it is, the behaviour is more close to what I was trying to achieve, however  it feels like is still stuck at the same distance and then it updates after a while.
I don't know if it is a limitation of the code and the GPS, or if some improvement in this sense could be done by playing around with the `gpsMinDistance` and `gpsTimeInterval` properties and if the gltf file is even more irresponsive due to the more complex nature of the object. I will upload a recording of my screen, it will be nice to know if the behaviour in your case is similar or you have better results, just to troubleshoot .

https://user-images.githubusercontent.com/79668392/109803095-eeac5080-7c20-11eb-94ed-e03d81d3d8c8.mp4


Thank you again

**Comment by dthery** [comment]
Yes @gabriele-lorusso i have the same thing but with a less blue sky. I've never seen a demo with solid tracking in geolocation. To display markers on a place is good, but to put a big model on the ground it's not solid. Ideally you should combine a flat surface detection in addition.

**Comment by gabriele-lorusso** [comment]
@dthery the flat surface is ideal (like sketchfab AR), even though I don't have a clue how to add it or if can be added so easily. What I am trying to achieve in this case allows for a bit of issues anyway, I am just trying to see if it could be improved. I might try to see if gelocation and image based detection could be mixed, as in previous experience that I had with an AR app if you take a photo of a place it can be use as trigger capable of recognise it even with different light conditions. I'll see what nick suggests and go on from that. Thank you for your feedback

**Comment by nickw1** [comment]
Hi @gabriele-lorusso it does tend to work better over larger distances (more than a few metres) partly due to the accuracy of GPS and the quality of the GPS device. You could try decreasing gpsMinDistance and gpsMinTime, the default settings are optimised for preventing jerky movement due to small position updates, but will cause the location to be updated less frequently.

To get an idea of what is currently possible with the technology look at this video: https://hikar.org/video/hikarweb.mp4.
You will note that you can move towards the augmented content, but there are small delays in updates (in any case you do not want to be updating continuously otherwise the battery will drain quickly).

Also, yes, flat surface detection is something we are hoping to add :-) Current time frame for working on this is the summer (June).

**Comment by gabriele-lorusso** [comment]
Thanks @nickw1 , I am looking into Google model viewer as well at the moment as per suggestion of @dthery . It's frustrating to see that it is great in terms of positioning the object in space but it's not clear how to force AR to start automatically and how to have a location based trigger, stuff that is great with this repository. I am sorry I cannot contribute with the coding as is not my everyday thing, it will be nice to have the GPS data only as trigger for the model and then have the "placing option".

Anyway thanks for your help, in this uncertain times is very appreciated. I will close the issue.
