### ISSUE TITLE
Can I import AR.js to react  or webpack now ?

### ISSUE THREAD

**Issue by pxim** [AR-js-org/AR.js#226]
**Do you want to request a *feature* or report a *bug*?**
I want  import AR.js to react.

**What is the current behavior?**
I don't know how to do it with  import AR.js to react .

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
ios13.4.1
safari

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
We are working on this feature see PR https://github.com/AR-js-org/AR.js/pull/116, see also issue https://github.com/AR-js-org/AR.js/issues/99

**Comment by kalwalt** [comment]
Yes you can we have also published the first npm beta packages https://www.npmjs.com/package/@ar-js-org/ar.js
you can install with npm:
```
npm i @ar-js-org/ar.js
```
and for additional infos read this issue https://github.com/AR-js-org/AR.js/issues/234
