### ISSUE TITLE
Keep content on screen even when not tracking marker

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/AR.js#23]
feature request from: https://github.com/jeromeetienne/AR.js/issues/313

**Comment by Kulcanhez** [comment]
"Using the marker camera is more stable than the entity camera if the camera's going to be moving around."

But I also read in some issue that the a-anchor is the new a-marker.

At the moment, I found:
a-anchor
a-marker
a-marker-camera

What's the difference between all of these? If the a-marker-camera is the best for camera movement, can I also use the smoothCount and others in that one?

In the [Docs](https://github.com/jeromeetienne/AR.js/tree/master/aframe) it also says to use <a-scene artoolkit>. Should I replace <a-scene embedded **arjs**='sourceType: webcam; trackingMethod: best; debugUIEnabled: false;> with artoolkit?

**Comment by nicolocarpignoli** [comment]
see : https://github.com/AR-js-org/AR.js/issues/96

**Comment by Zaniyar** [comment]
What is the equivalent 
<a-marker-camera preset="hiro"></a-marker-camera>
for Three.js?
