### ISSUE TITLE
[location-based] Content 'sticking to' camera on certain devices

### ISSUE THREAD

**Issue by nickw1** [AR-js-org/AR.js#275]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

This issue is to discuss the behaviour originally documented in issue #265, and possibly elsewhere.
Namely, on some devices, location-based content specified with `gps-entity-place` appears to 'stick' to the camera even if you move around.

**If the current behavior is a bug, please provide the steps to reproduce.**

Try going to this URL: (265 was the original issue number)

https://hikar.org/265/

What this is supposed to do, is automatically create two boxes a short distance to your north as soon as it gets a GPS position (wherever in the world you are)

If you walk away from your original position in directions other than north, the boxes should get smaller, but if you walk north, they should get bigger.

On some devices, this behaviour is not seen and instead the two boxes 'stick' to the camera.

As an initial step to try and diagnose the problem, could you report:
- Phone model
- OS and version
- Browser and version
- Approximate location (at country level)

if the expected behaviour is not occurring.

What would be also good is if you could (if using Chrome on the mobile device) setup Chrome Developer Tools and see if any errors are reported:
https://developer.chrome.com/docs/devtools/remote-debugging/

@nicolocarpignoli any ideas? I think people have reported this issue before, the issue of @EchoDeltaMoon was similar.

Thanks.

**Comment by maletiger0404** [comment]
Hi @nickw1  I have tested it on iPhone X 14.2.2 and I got the issue.
It just appears everywhere am I.

**Comment by maletiger0404** [comment]
Hi, @nickw1  the GPS was working correctly with the @jrmasiero's code in Australia but now it's not working.
Can you please revoke the code, you updated?

**Comment by maletiger0404** [comment]
@nicolocarpignoli  can you please help me?

**Comment by nickw1** [comment]
@maletiger0404 what do you mean revoke the code?
AFAIK I didn't change anything to stop this working.

The site at https://hikar.org/265/ is a demo for people to test whether GPS is working correctly on their devices; I do not want to unpublish it because the findings from it could be helpful.

**Comment by maletiger0404** [comment]
yes, GPS is working correctly. I have already tested it for many times.

**Comment by maletiger0404** [comment]
https://github.com/AR-js-org/AR.js/issues/265#issuecomment-840602693

In here, after changing the locations to my locations, I tested it and it was working correctly and I didn't change any code.
But it's not working now.
Didn't you change any code of the library?

**Comment by maletiger0404** [comment]
What is the basic working principle of AR.js?
Why it is not working, still?

**Comment by nickw1** [comment]
@maletiger0404 when did you change it?
Version 3.3.3 was released about 10 days ago. 

The test site https://hikar.org/265/ definitely works with that, as do a number of other examples.

Since then, no - nothing's changed.

**Comment by nickw1** [comment]
@maletiger0404 also looking at that code, it only gets the GPS position when the page first loads, or when the user touches the screen. Is that intentional? If you use watchPosition() rather than getCurrentPosition() it will continuously update.

**Comment by maletiger0404** [comment]
> @maletiger0404 when did it stop working?
> Version 3.3.3 was released 11 days ago, on the 8th.
> 
> The test application https://hikar.org/265/ definitely works with that on my device, as I created it after the above release, as do a number of other examples.
> 
> Since then, no - nothing's changed.

So this link is working now exactly?

**Comment by maletiger0404** [comment]
> @maletiger0404 also looking at that code, it only gets the GPS position when the page first loads, or when the user touches the screen. Is that intentional? If you use watchPosition() rather than getCurrentPosition() it will continuously update.

I want to disable the touchable screen. How can I do it?

**Comment by maletiger0404** [comment]
> @maletiger0404 do other _web-based_ applications using the GPS work? In other words applications using the geolocation API?
> 
> Try and find some examples on the web which make use of the geolocation API and see if they work.
> 
> What browser are you using? It will be helpful if you can somehow look at the browser console to see if any errors are being reported; I have already explained how to do this in Chrome, I'm guessing Safari will have similar functionality.

I couldn't find the location-based AR app for the web.

**Comment by maletiger0404** [comment]
Hi @nickw1 
I tested the  https://hikar.org/265/.
I have walked away from the cubes but it's not smaller.
I will share a video

**Comment by maletiger0404** [comment]
Can you please share a video on your end?
I want to see a video when you walk away from the cube.

**Comment by nickw1** [comment]
@maletiger0404 some of these questions are getting a bit OT and cluttering up the issue. Can you ask general questions in the discussions? Thanks.

**Comment by maletiger0404** [comment]
I have walked away from the cubes but the size is not updated.

**Comment by nickw1** [comment]
@maletiger0404 Sorry to have to mention this, but could I ask once again, if you want general support, please use the discussions. There is a possible bug in AR.js leading to this behaviour, but to find out what is causing this, we need to know what devices the bug occurs on.

This issue is aimed at gathering this information, and getting ideas from people what might be causing the bug. Please do use the discussions part of the repository if you would like general support. Thanks.

**Comment by nicolocarpignoli** [comment]
@maletiger0404 

I have to agree totally with @nickw1 about this. 
There is probably a bug on AR.js showing this problem for some devices. It is not easy for us to understand this, because on most devices, AR.js location based works ok.

So, @nickw1 had a great idea to open this issue and try to understand, with the help of contributors, the problem. This is the best way to do that.
Your behaviour, on this issue, is blocking the discussion.
I have told this you already in another issue: the solution is not to post messages everywhere and tag us constantly. If you need to solve this urgently, either you pay someone or you do it by yourself.

This was an "ethical" suggestion about Open Source but now it has become a problem for the management of this issue and the repository itself.

So, we are going to do this: we are closing this issue, opening a new one in order to understand this problem and collect users feedbacks.
About your requests, I suggest you use the Discussion, ask a question on Stackoverflow or write on Gitter chat. You have plenty of options for debugging and this kind of help requests.

https://github.com/AR-js-org/AR.js/discussions
https://stackoverflow.com/
https://gitter.im/AR-js/Lobby

You have plenty of **correct** options to use instead of your current behaving.

If you will start again this kind of requests as off topics, I will block or hide your comments.
I hope I do not need to come at that as I never had to do, and for sure do not want to start now :)

@nickw1 please re-open this issue if you don't bother. 
Cheers.

**Comment by nickw1** [comment]
Reopened as #278.

**Comment by yedianyang** [comment]
Hi
Just want to let you know there might be some problem that this function not working well in China( not sure). I try [this](https://hikar.org/265/) on three devices. The dialogue box pops out successfully every time when I refresh the site and got the right GPS reading. But all the box sizes are not changed corrsponding when I walking. It moves at the same time when I move.

Three devices are:
1. iPhone 12 pro max
    IOS 14.3
    Chrome for IOS 86.0.4240.93 / Firefox Daylight 34.0(4920)

2. iPhone 6s
    IOS 13.6.1
    Safari

3. iPad Pro 11 inch 2019 cellular (with GPS)
    ipadOS 14.4
    Chrome for ipadOS 90.0.4430.216 / Firefox Daylight 34.0(4920)

And I am in Shanghai, China.

Best.

**Comment by nickw1** [comment]
Hi @yedianyang thanks for your report. Could you re-post it in issue #278? This issue has been closed as it was getting cluttered.

I don't think it's to do with your location in China. It's likely to be dependent on your devices, so many thanks for reporting your device details - that will help diagnose the problem.
