### ISSUE TITLE
Examples not working: "Loading, please wait..." 

### ISSUE THREAD

**Issue by doncabreraphone** [AR-js-org/AR.js#277]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
The example for the Image Tracking is not working. I tried it with 4 different browsers but nothing. Firefox, Chrome, Opera, and Brave. All of them updated to their latest build. I open the [provided link](https://ar-js-org.github.io/AR.js/aframe/examples/image-tracking/nft/) from the example and gave the program access to my phone's camera, but it stays in the "Loading, please wait..." forever. The other examples (location and marker) are working just fine.

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
My phone is a Xiaomi Realme 6, Android 11

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by bamz3r** [comment]
open page in your desktop browser, and take a look at javascript console. it should be an error information

**Comment by arapps3d** [comment]
I have exactly the same issue. console says "Error in loading marker on Worker 404".

**Comment by gi4no** [comment]
there is an error in the example.

https://github.com/AR-js-org/AR.js/blob/aaad9847f67a4738b00724c38d9f501d78e0a8af/aframe/examples/image-tracking/nft/index.html#L39

this path ./aframe/examples/image-tracking/nft/trex/trex-image/trex as to be ./trex/trex-image/trex.

how can i submit a PR?

**Comment by arapps3d** [comment]
> 
> 
> there is an error in the example.
> 
> https://github.com/AR-js-org/AR.js/blob/aaad9847f67a4738b00724c38d9f501d78e0a8af/aframe/examples/image-tracking/nft/index.html#L39
> 
> this path ./aframe/examples/image-tracking/nft/trex/trex-image/trex as to be ./trex/trex-image/trex.
> 
> how can i submit a PR?

I have changed the URL but it's still the same error.

**Comment by doncabreraphone** [comment]
Same issue described above. It is not working. The other examples are, but
not this one.

**Comment by gi4no** [comment]
my working code

`  <a-scene
    vr-mode-ui="enabled: false;"
    renderer="logarithmicDepthBuffer: true;"
    embedded
    arjs="trackingMethod: best; sourceType: webcam; debugUIEnabled: false;"
  >
    <a-entity
      light="color: #ffffff; intensity: 5"
      position="-1 1 100"
    ></a-entity
    >x
    
    <a-nft
      type="nft"
      url="./trex/trex-image/trex"
      smooth="true"
      smoothCount="10"
      smoothTolerance="0.01"
      smoothThreshold="5"
    >
      <a-entity
        gltf-model="./trex/scene.gltf"
        scale="20 20 20"
        position="0 40 -20"
      >
      </a-entity>
    </a-nft>
    <a-entity camera></a-entity>
  </a-scene>`

**Comment by arapps3d** [comment]
sorry, still not working for me; also not working with the code / new urls- does anybody have this working example online to test?

**Comment by bamz3r** [comment]
just change path to ./trex/trex-image/trex

and make sure open the page over https, if you open from localhost will not working.

**Comment by arapps3d** [comment]
also over https it does not work -  I changed the path
check
https://www.arapps3d.de/AR.js-master/aframe/examples/image-tracking/nft/

**Comment by doncabreraphone** [comment]
How can this be a closed issue, when I follow the example on this very documentation and I get the error?

**Comment by bamz3r** [comment]
Ok. tested now working with realtive path url to 'root' of your domain

example
/AR.js/aframe/examples/image-tracking/nft/trex/trex-image/trex

**Comment by arapps3d** [comment]
> 
> 
> Ok. tested now working with realtive path url to 'root' of your domain
> 
> example
> /AR.js/aframe/examples/image-tracking/nft/trex/trex-image/trex

Thanks! This finally works for me (full url with https). 
Unfortunately the tracking of the Trex on the image seems really unstable (at least on Galaxy S8 in Chrome).

**Comment by Wulff2099** [comment]
i have the same problem, 
loading marker on worker 404

**Comment by KieranCollins** [comment]
I still have this issue. None of the above advice worked.

**Comment by Wulff2099** [comment]
Yes i read about it its ok hope you can fix it soon

**Comment by PeraDev7** [comment]
Any updates?

**Comment by qianxifu** [comment]
same issue i got this error :
device:error WebXR session support error: Cannot read properties of null (reading 'hasLoaded')  browser.js:111

**Comment by kalwalt** [comment]
updated new link in the [README](https://github.com/AR-js-org/AR.js/blob/master/README.md) now use this one: https://ar-js-org.github.io/.github/profile/aframe/examples/image-tracking/nft/ 
linked issue #529
