### ISSUE TITLE
Empty dialog with pink button in iPhone devices

### ISSUE THREAD

**Issue by SheikhZayed** [AR-js-org/AR.js#279]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Everything works fine, except a blank dialog with pink button which is really weird, please check the following image

![WhatsApp Image 2021-05-23 at 9 06 43 AM](https://user-images.githubusercontent.com/8774293/119249031-a01aac80-bba6-11eb-9c9f-4ad445b61e65.jpeg)

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**
This dialog appears only in iPhone devices, every other browser works fine,

**What is the expected behavior?**
empty dialog should not appear

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by rondog** [comment]
check to make sure your CSS is not overriding the text color in that dialog. I thought I had run into the issue of it being blank, however, the text was there and my body css had a color of white that was overriding this dialog

**Comment by SheikhZayed** [comment]
@rondog exactly, that was the issue ... i fixed it
