### ISSUE TITLE
Location Based: content follows the camera when moving phone on y axis

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/AR.js#28]
see: https://github.com/jeromeetienne/AR.js/issues/710

**Comment by nicolocarpignoli** [comment]
fixed with aframe 1.0.4

**Comment by jtm7878** [comment]
> fixed with aframe 1.0.4

Where is link to bug fix? I am having same issue of camera markers following camera

**Comment by williamqian** [comment]
I have used these versons of aframe：0.9.2、1.0.4、1.1.0,but nothing changed,the 3d model follow my mobile all the time.
