### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by gushenjie** [AR-js-org/AR.js#280]
![image](https://user-images.githubusercontent.com/10531802/119332191-d77a7d80-bcba-11eb-9b68-f1b5c5df2e73.png)

![image](https://user-images.githubusercontent.com/10531802/119332259-ecefa780-bcba-11eb-8306-689ad6fa0137.png)

<script src='../../../build/aframe.min.js'></script>

<style>
  .arjs-loader {
    height: 100%;
    width: 100%;
    position: absolute;
    top: 0;
    left: 0;
    background-color: rgba(0, 0, 0, 0.8);
    z-index: 9999;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .arjs-loader div {
    text-align: center;
    font-size: 1.25em;
    color: white;
  }
</style>

<script src='../../../build/aframe-ar-nft.js'></script>

<body style='margin : 0px; overflow: hidden;'>
   
  <div class="arjs-loader">
    <div>Loading, please wait...</div>
  </div>
    <a-scene
        vr-mode-ui='enabled: false;'
        renderer="logarithmicDepthBuffer: true;"
        embedded arjs='trackingMethod: best; sourceType: webcam; debugUIEnabled: false;'>

        
        <a-nft
            type='nft' url='./aframe/examples/image-tracking/nft/trex/trex-image/trex'
            smooth='true' smoothCount='10' smoothTolerance='0.01' smoothThreshold='5'>
            <a-entity
                gltf-model='./trex/scene.gltf'
                scale="5 5 5"
                position="150 300 -100"
                >
            </a-entity>
        </a-nft>
		<a-entity camera></a-entity>
    </a-scene>
</body>

**Comment by gushenjie** [comment]
<script src='../../../build/aframe.min.js'></script>

<style>
	.arjs-loader {
    height: 100%;
    width: 100%;
    position: absolute;
    top: 0;
    left: 0;
    background-color: rgba(0, 0, 0, 0.8);
    z-index: 9999;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .arjs-loader div {
    text-align: center;
    font-size: 1.25em;
    color: white;
  }
</style>


<script src='../../../build/aframe-ar-nft.js'></script>

<body style='margin : 0px; overflow: hidden;'>
	
	<div class="arjs-loader">
		<div>Loading, please wait...</div>
	</div>
	<a-scene vr-mode-ui='enabled: false;' renderer="logarithmicDepthBuffer: true;" embedded arjs='trackingMethod: best; sourceType: webcam; debugUIEnabled: false;'>

		
		<a-nft type='nft' url='./aframe/examples/image-tracking/nft/trex/trex-image/trex' smooth='true' smoothCount='10'
		 smoothTolerance='0.01' smoothThreshold='5'>
			<a-entity gltf-model='./trex/scene.gltf' scale="5 5 5" position="150 300 -100">
			</a-entity>
		</a-nft>
		<a-entity camera></a-entity>
	</a-scene>
</body>

**Comment by gushenjie** [comment]
![image](https://user-images.githubusercontent.com/10531802/119332433-2a543500-bcbb-11eb-87ed-ae4752e63313.png)

**Comment by karltaylor** [comment]
Hello,

Check that you are serving your NFT marker correctly. It is a bit of a cryptic error message but this happened to me when it couldn't load the marker.

**Comment by Sadji0** [comment]
Hi. 
I tryed to use your example in README as "Image tracking", but it's not wroking. Loop loading and eat much browser memory. 
What should I do now?

**Comment by gushenjie** [comment]
mee to

**Comment by nickw1** [comment]
Hi @Sadji0 @gushenjie please note that issues are for reporting bugs, and getting input from people on how they might be able to be resolved. Please use the 'Discussions' for general support (https://github.com/AR-js-org/AR.js/discussions). Thanks!

**Comment by gushenjie** [comment]
![image](https://user-images.githubusercontent.com/10531802/122151873-e6f07f00-ce92-11eb-9beb-c4a3402699d3.png)

Fully used the official demo to run, always reporting errors

**Comment by gushenjie** [comment]
https://topvision-cv.com/rtc/AR.js/aframe/examples/image-tracking/nft-video/index.html

**Comment by gushenjie** [comment]
> Hello,
> 
> Check that you are serving your NFT marker correctly. It is a bit of a cryptic error message but this happened to me when it couldn't load the marker.

Fully used the official demo to run, always reporting errors

**Comment by gushenjie** [comment]
i solve it use nodejs start
