### ISSUE TITLE
'formatDistance' has already been declared

### ISSUE THREAD

**Issue by washanhanzi** [AR-js-org/AR.js#285]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

when compiling the js file:

`'formatDistance' has already been declared`

`aframe-ar-location-only.js:1865:9`

**If the current behavior is a bug, please provide the steps to reproduce.**

in `/aframe/build/aframe-ar-location-only.js`, line 1244 and line 1865 have two identical function `formatDistance`

**Comment by nickw1** [comment]
Fixed this on dev by moving `formatDistance()` into the components. Not the ideal solution, would be better to create a `utils` object or similar, but will wait until the ES6 branch is ready.
