### ISSUE TITLE
Image Marker example is not working on Android (galaxy S8, chrome)

### ISSUE THREAD

**Issue by TheBricktop** [AR-js-org/AR.js#297]
**Do you want to request a *feature* or report a *bug*?**

Bug.
**What is the current behavior?**
The trex example image is not getting recognized .
**If the current behavior is a bug, please provide the steps to reproduce.**
1. opened the "open this live example" in chrome android
2. opened the trex image provided on screen of a mac (pretty bright and high quality screen i can assure You)
3. allowed camera and endlessly waited for a trex to emerge.

yes
**Please mention other relevant information such as the browser version, Operating System and Device Name**
Samsung galaxy s8 android chrome
**What is the expected behavior?**
The trex should be rendered above scanned trex image.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
see #529
