### ISSUE TITLE
How can I cite this project? 

### ISSUE THREAD

**Issue by dyllanwli** [AR-js-org/AR.js#300]
I am currently working on a scientific project with the AR.js framework. How can I cite this project?

**Comment by nickw1** [comment]
Might need @nicolocarpignoli's input here, but I would imagine you would credit the lead authors primarily, i.e. Jerome Etienne and Nicolò Carpignoli.

Etienne, J., Carpignoli N. and contributors (2021) "AR.js - Augmented Reality for the Web", online, available at: [URL] last accessed on: [date].

**Comment by nicolocarpignoli** [comment]
Yes, at least please cite Jerome Etienne, the original maintainer and creator.
I found this paper and I think this quote is quite good:

`Etienne, Jerome , Nicolò Carpignoli, and AR.js Org Community. n.d. AR.js - Augmented Reality on the Web. AR.js Ducumentation. Accessed Mei 2, 2020. https://ar-js-org.github.io/AR.js-Docs/.`

from  https://ejournal.stmik-wp.ac.id/index.php/ictech/article/view/90
