### ISSUE TITLE
Object.assign no longer works for three.js EventDispatcher prototype

### ISSUE THREAD

**Issue by dbartussek** [AR-js-org/AR.js#334]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Using Ar.js with the newest version of three.js (r128) causes calls to dispatchEvent to fail. This is because using Object.assign(*target*, THREE.EventDispatcher.prototype) does not copy over anything.

**If the current behavior is a bug, please provide the steps to reproduce.**
Use any example with the current build of [three.js](https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.js).

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Windows 10, Edge Chromium version 83.
UserAgent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.38`

**What is the expected behavior?**
Replacing Object.assign with `"target".prototype = new THREE.EventDispatcher()` works as a bandaid. I am not sure if this is the proper way to fix the issue, but the prototype assignment code will have to be fixed for Object.assign no longer enumerating the methods.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
@dbartussek if you want i fixed this in the ES6 branch see https://github.com/AR-js-org/AR.js/pull/116#issuecomment-967492560 PR https://github.com/AR-js-org/AR.js/pull/116, if i will have time i will fix also in dev/master branch. :smile:

**Comment by kalwalt** [comment]
@dbartussek The fix now is in dev branch, can you test it?

**Comment by kalwalt** [comment]
closing because no response
