### ISSUE TITLE
Can 3D objects be displayed via camera and body/facial recognition and tracking? 

### ISSUE THREAD

**Issue by AHRealift** [AR-js-org/AR.js#343]
**Do you want to request a *feature* or report a *bug*?**

Can 3D objects be displayed via camera and body/facial recognition and tracking? 

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by nicolocarpignoli** [comment]
Nope, it is not supported as for now. No ETA for this features, sorry. You can check jeeliz AR (and jeeliz AR face filters)
