### ISSUE TITLE
5x5 markers not being recognised

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/AR.js#37]
see: https://github.com/jeromeetienne/AR.js/issues/730

**Comment by kalwalt** [comment]
@nicolocarpignoli @ThorstenBux think we can add this feature in the near future, really it is an easy add! Just few modify in jsartoolkit5...

**Comment by SamL86** [comment]
Hi @kalwalt, 5x5 still isn't working. Can you tell me what I need to edit to enable?
Thanks

**Comment by kalwalt** [comment]
New markers Barcode implemented with PR #469
