### ISSUE TITLE
Location based change real world positions when mobile orientation change

### ISSUE THREAD

**Issue by DavidGonzalezGutierrez** [AR-js-org/AR.js#376]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Having a point in specific coordinates, depending on where the mobile is looking when starting the website, that point moves, that is, it is not in its position in the real world

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

Tested on Xiaomi Mi 9T with chrome browser.

**What is the expected behavior?**

If I have a point in some coordinates, that point must not move from its position in the real world.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by nickw1** [comment]
@DavidGonzalezGutierrez sounds like it's related to #278 , does that sound right?

If so, if you look at that issue, there's a site to test whether it should, in theory, work on your device. See the last post on that issue.

**Comment by DavidGonzalezGutierrez** [comment]
I think is not the same problem.

I mean when you have an entity in real world coordinates, for example a church in your city.

This church is pointed to real world north for example.

If you start with your phone looking to the north, the church appears in the correct real world side.

But If you start look to the south, the church appears on south.

Maybe, I think is related by I create the location based objects directly in aframe instead of create the scene and after place the objects.

I'm going to do more test, and if I don't find the bug, I share an example code.

**Comment by nickw1** [comment]
@DavidGonzalezGutierrez ok thanks. Yes it would be good to see your code.

**Comment by fermarci** [comment]
Hi, i have the same problem. i'm using iphone 12 mini, but tested on other iphones as well. 
My source code is very simple is based on one of the examples:
`<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>GeoAR.js demo</title>
    <script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
    <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>
  </head>

  <body style="margin: 0; overflow: hidden;">
    <a-scene
      vr-mode-ui="enabled: false"
      embedded
      arjs="sourceType: webcam; debugUIEnabled: true;"
    >

     <a-box material="color: red;" scale="1 1 1" gps-entity-place="latitude: 44.50439; longitude: 11.30091;"></a-box>
     <a-camera
            rotation-reader
            gps-camera="simulateLatitude: 44.50437; simulateLongitude: 11.30106; gpsMinDistance: 10;"
        >
		    </a-camera>
    </a-scene>
  </body>
</html>`

the live demo is available here:
[https://www.c3.hu/~marci/im/t.html](url)

the screen video is available here:
[https://youtu.be/Vo7_u01czxE](url)

**Comment by nickw1** [comment]
@DavidGonzalezGutierrez  @fermarci sorry for the late reply on this. This sort of behaviour normally occurs on Firefox, not Chrome, as Firefox cannot recognise north.

Try out the pure three.js location based API from the latest commit to master, and see if that works correctly.

I am re-writing the A-Frame location based components to make them simpler and easier to understand (and thus easier to debug) but this isn't quite ready yet.

**Comment by fermarci** [comment]
Hi, thanks for your reply. i tried the three.js version, but i was not able to make it work. i have an ios device, and according to the readme it is not working on ios. no objects are visible.

i've tried to make a version where i place the objects dynamically to the starting location. it is working on the "fakeGPS" mode but not when i have real data.
[https://www.c3.hu/~marci/im/tr2.html](https://www.c3.hu/~marci/im/tr2.html)

do you have any idea?

rgds
m

**Comment by nickw1** [comment]
@fermarci  There were one or two bugs with the location based example, these are fixed in #409 so just waiting to merge.

**Comment by nickw1** [comment]
Merged now, see the latest commit on `dev`. In particular see the revised example: https://github.com/AR-js-org/AR.js/blob/dev/three.js/examples/location-based/index.js

**Comment by nickw1** [comment]
@fermarci great! Could you submit a PR with your changes?
