### ISSUE TITLE
Add a `maxDistance` property, opposite to minDistance on Location Based

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/AR.js#38]
see: https://github.com/jeromeetienne/AR.js/issues/727

**Comment by jmchat** [comment]
Any ETA on when this very welcome featue will be live?

**Comment by nicolocarpignoli** [comment]
No ETA but it should not be too difficult to do. If I found time to do that, would you mind testing it?

**Comment by jmchat** [comment]
Sure I would test it right away :-)

**Comment by nicolocarpignoli** [comment]
@jmchat https://github.com/AR-js-org/AR.js/pull/89

**Comment by jmchat** [comment]
@nicolocarpignoli it works fine for me! even on my old iPhone the box appears when I'm close and disappears when I walk away form the box.  (in my testcase 1-5 meters)

Thnx for you quick response 👌

**Comment by nicolocarpignoli** [comment]
will be released on new version, feature is now merged on dev
