### ISSUE TITLE
White_region Markers not properly working

### ISSUE THREAD

**Issue by rafelis1997** [AR-js-org/AR.js#384]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
White region markers not being recognized

**If the current behavior is a bug, please provide the steps to reproduce.**

Tested on Android 11 smarthphone, labelingMode not working and showing this report in the console.log:

"aframe-ar.js:2485 THREEx.ArToolkitContext: 'labelingMode' is not a property of this material."

The .html exemple of this feature is also not working, so you can easily reproduce it.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Tested on Android Chrome version 97.0.4692.98 and Desktop Chrome version 97.0.4692.99

**What is the expected behavior?**
Marker not being detected

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
I can reproduce the bug, i will try to fix it as soon i can in PR #359

**Comment by kalwalt** [comment]
@rafelis1997 i fixed in #359 with commit https://github.com/AR-js-org/AR.js/commit/5912a844ee6c28f426f76e68841a4497c5971713. The white markers works as expected now, I will fix this bug also in the master branch.

**Comment by rafelis1997** [comment]
It's working, not accurate but works. The algorithm struggles a bit with inverted markers  do you know why?
