### ISSUE TITLE
Location based click places issue

### ISSUE THREAD

**Issue by antoniskamzel** [AR-js-org/AR.js#388]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Places that are further than about 1km (1000 meters) away from the user-phone cannot be clicked and trigger an action. I am able to click places that are 400, 600, 890 meters away (with my testing)

**If the current behavior is a bug, please provide the steps to reproduce.**

Just use click places code but put places that are more than 1km away from the user. I've tried making the scale much bigger but with no result

**Comment by antoniskamzel** [comment]
I have changed the near and far attributes of `a-camera` but not raycaster as u say. I will try it and come back later

**Comment by antoniskamzel** [comment]
So the issue got fixed when i changed the raycaster near and far. Thanks for the help!

**Comment by nickw1** [comment]
@antoniskamzel glad you got this one sorted out!
