### ISSUE TITLE
Error code 429 ABORTED and AR wont load

### ISSUE THREAD

**Issue by antoniskamzel** [AR-js-org/AR.js#389]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Importing ar.js scripts gives me error code 429 saying `GET https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js net::ERR_ABORTED 429` . And when i copy-paste the url into a browser it says `(429) Too many requests`

**Comment by kalwalt** [comment]
It's not a AR.js bug it depends on raw.githack limits. Read the raw.githack FAQ and [this](https://raw.githack.com/#development-in-production) and [this](https://raw.githack.com/#what-happens-to-jerks)
