### ISSUE TITLE
Places more than 1km wont load

### ISSUE THREAD

**Issue by antoniskamzel** [AR-js-org/AR.js#390]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

in Location-based it seems that places more than 1km away from the phone won't show up despite having `far` value more than 1000 meters. It worked with the SAME code until 2 days before. I didnt change anything in my code and suddenly it doesn't work. Some places that are about 1km away will show when having them in the center of the screen and won't show if they are at the edges... Note 1) i have tried setting webcam-texture to true but it doesn't work as when i make it true, the AR.js script won't load. Note 2) I've noticed that when i click at a direction that i know that a place should show-render, it gets clicked! I can't see it though, but it can be clicked and shows me the info that i want (it is more than 1km away). Note 3) When i set the `far` to something like 10-50 (so nothing would show - no places so close) it still shows places that are as far as 1km away. Like it ignores the far attribute of the `a-camera`. Note 4) I have tried setting the gps-camera attributes `minDistance` and `maxDistance` to very small numbers but still places render as far as 1km.

**If the current behavior is a bug, please provide the steps to reproduce.**

Just load the code from click-places and add a place more than 1km away

**Comment by kalwalt** [comment]
Hi @antoniskamzel which branch are you using? Recently i fixed a bug https://github.com/AR-js-org/AR.js/commit/99bda004452549e8a7576b9e7afc26992aa0104e for issue #384 but wasn't related to location based. I can't say more to help, but maybe @nickw1 can have some insight.

**Comment by antoniskamzel** [comment]
@kalwalt What do you mean bu 'branch' ? Im kinda new to all this but here is the scripts that i include
<script src='https://aframe.io/releases/0.9.2/aframe.min.js'></script>
   <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>
    <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
    <script>
        THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/jeromeetienne/ar.js/master/three.js/'
    </script>

**Comment by nickw1** [comment]
This is a known artefact if `videoTexture` is not set to true.

@antoniskamzel you say it doesn't work if 'videoTexture` is set to `true`, you say the AR.js script does not load. Does the browser console give you any errors?

One problem I did notice earlier in the week was that githack was not serving the AR.js code; if you say it worked one day and not the next, is this a possible explanation?

**Comment by nickw1** [comment]
To add to that, I have been meaning for a while to rewrite the A-Frame component to wrap the recently-introduced pure three.js implementation. I know the code better (Nicolò has little time to work on the project now) so this will help maintenance and bug-fixing I suspect.

I'm rather busy with the day job during the winter months, but hope to spend some time on this soon (as well as write a tutorial for the pure three version).

**Comment by antoniskamzel** [comment]
@nickw1
![Screenshot 2022-02-20 161124](https://user-images.githubusercontent.com/72403002/154847053-7738bbe7-6e7e-4a6f-8cd3-b2bb83f0adb0.jpg)
![Screenshot 2022-02-20 161456](https://user-images.githubusercontent.com/72403002/154847058-8654c47f-bf9e-400f-8384-5844f16c3696.jpg)
So in the first screenshot you see the console with no `video-texture` attribute and the second screenshot is when i add video-texture with true value. So no errors whatsoever, so i assume it just doesnt load the ar.js code (the 'added event (74)' is a console.log that i include for every a-image that i add dynamically and as u can see it is not logged in the second screenshot.)
But yeah, if you noticed some weird behavior (not serving code)  it could be something with the AR.js code. And from the moment that it just broke from one day to another it could be something like that?! But why `video-texture` is breaking the code? Maybe a bug? Or a version thing? Check the screenshots to see the versions that i use (if i change a-frame version to 1.2.0 e.g. the 'click listener' doesn't work so that's why i have 0.9.2)

**Comment by nickw1** [comment]
@antoniskamzel is your complete code available? (So I can test it, when I have a moment). V

Also click listeners should work in newer versions of A-Frame. You do need to include the `raycaster` (as I mentioned in the other issue) and also add a `cursor` component to the `<a-scene>`, giving it a `rayOrigin` property of `mouse`. e.g.

`<a-scene cursor='rayOrigin: mouse' .... `

This sets the origin of the ray used for detecting intersections to be the mouse click position.

**Comment by nickw1** [comment]
Note though, in a follow up to my previous comment, I have not tested click events on `<a-image>`s, only primitives and models.

**Comment by antoniskamzel** [comment]
okay here is the whole code: 
`
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <script src='https://aframe.io/releases/0.9.2/aframe.min.js'></script>
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>
    <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
    

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    
</head>

<link rel="stylesheet" href="./icons/index.css">

<body style='margin: 0; overflow: hidden;'>
    <a-scene
        cursor='rayOrigin: mouse; fuse: true; fuseTimeout: 0;'
        raycaster="objects: [gps-entity-place];"
        vr-mode-ui="enabled: false"
		embedded
		arjs='sourceType: webcam;  sourceWidth:1280; sourceHeight:960; displayWidth: 1280; displayHeight: 960; debugUIEnabled: false;'>

        <a-camera gps-camera rotation-reader>
		</a-camera>
	</a-scene>
</body>

<script>
//!!!!!!!!!!!NOTE THAT IS THIS THE EXACT SAME CODE THAT I SAID WAS WORKING THE OTHER DAY AND THEN IT STOPPED WORKING, NO CHANGES MADE

const loadPlaces = function(coords) {
    PLACES = [];
    return Promise.resolve(PLACES); 
};

async function axiosCall(places){
    await axios.get('here goes the site from where i download data for my places (including lat and long values)').then(resp => {
                        
                        resp.data.forEach(element => {
                            var n = element.description;
                            var loc = {lat:0, lng:0};
                            loc.lat = parseFloat(element.lat);
                            loc.lng = parseFloat(element.lng);
                            var icon = element.ar_icon;
							//var place is the important, ignore the rest
                            var place = {name: n, location: loc, img: icon};
                            places.push(place);
                            
                        });
                        
                })
}


window.onload = () => {


    const scene = document.querySelector('a-scene');

    return navigator.geolocation.getCurrentPosition(function (position) {

        
        loadPlaces(position.coords)
            .then((places) => {
               

                axiosCall(places).then(function() {
                                
                                places.forEach((place) => {
								
                                    //lat and long values for each image loaded
                                    const latitude = place.location.lat;
                                    const longitude = place.location.lng;
                                   
                                    const icon = document.createElement('a-image');
                                    icon.setAttribute('gps-entity-place', `latitude: ${latitude}; longitude: ${longitude}`);
                                    icon.setAttribute('name', place.name);
                                    
                                    icon.setAttribute('src', place.img);
                                    icon.setAttribute('look-at', '[gps-camera]');

                                    icon.setAttribute('scale', '50, 50');

                                    icon.addEventListener('loaded', () => window.dispatchEvent(new CustomEvent('gps-entity-place-loaded')));

                                    const clickListener = function(ev) {
                                        ev.stopPropagation();
                                        ev.preventDefault();

                                        const name = ev.target.getAttribute('name');
                                        const dis = ev.target.getAttribute('distancemsg');

                                        const el = ev.detail.intersection && ev.detail.intersection.object.el;

                                        if (el && el === ev.target) {
                                            const label = document.createElement('span');
                                            const container = document.createElement('div');
                                            container.setAttribute('id', 'place-label');
											
                                            if(dis==null){
                                                label.innerText = name + '\n' + 'Loading distance...';
                                            }
                                            else{
                                                label.innerText = name + '\n' + dis;
                                            }
                                            
                                            container.appendChild(label);
                                            document.body.appendChild(container);

                                            setTimeout(() => {
                                                container.parentElement.removeChild(container);
                                            }, 1500);
                                        }
                                    };

                                    icon.addEventListener('click', clickListener);
                                    console.log('added event');
                                    
                                    scene.appendChild(icon);
                                //close of foreach
                                });
                            //close of axioscall
                            });



                
            })
    },
        (err) => console.error('Error in retrieving position', err),
        {
            enableHighAccuracy: true,
            maximumAge: 0,
            timeout: 27000,
        }
    );
};

</script>`

**Comment by antoniskamzel** [comment]
@nickw1 okay so here is the full cod
[AR.txt](https://github.com/AR-js-org/AR.js/files/8111958/AR.txt)
e

**Comment by nickw1** [comment]
@antoniskamzel I don't think `videoTexture` works in `embedded` mode; only in full-screen. (Not completely sure though, I need to check this). I know I have had problems with AR.js and `embedded` mode in the past, though I can't remember the exact issue.

**Comment by nickw1** [comment]
... definitely the 1km distance limit is a known issue if you don't use `videoTexture`, I had that problem in 2020 which is why I implemented `videoTexture`.

**Comment by antoniskamzel** [comment]
@nickw1 so what is your suggestion? did you test it? If you tested, please upload the updated code so i can test it too with my data.
And if it worked now, how do you explain that all this time that i used `embedded` and no `videoTexture` it worked fine and then suddenly it stopped?

**Comment by AmirHossein-nr** [comment]
@antoniskamzel Hi There ! I Deleted "embedded" part in my code and it is Ok Now :) Try it . Maybe it fixes your code too

**Comment by antoniskamzel** [comment]
@nickw1 @AmirHossein-nr  seems that `embedded` was the issue, i removed it and now everything seems to be working fine again (`videoTexture` works now, as well as `far` etc)

**Comment by nickw1** [comment]
@antoniskamzel @AmirHossein-nr glad you got it working.

For me, >1km places have never been visible without `videoTexture`. Perhaps with `embedded` they are, not sure, haven't used `embedded` mode i have to admit.

If the AR locations are not exact, this is likely to be due to a) inaccuracies in the phone's sensors and b) there does seem to be an issue where the camera feed is distorted slightly near the edges of the device. We haven't yet resolved that.

**Comment by antoniskamzel** [comment]
@nickw1 okay, hope u get it sorted out soon. Thanks for the guidance and helping me resolving the issue!
