### ISSUE TITLE
Examples are written like shit 

### ISSUE THREAD

**Issue by Deja-vuuu** [AR-js-org/AR.js#420]

**Comment by kalwalt** [comment]
Hi @Deja-vuuu please provide constructive feedback on how the examples could be improved intead to use bad words or unappropriate comments. In respect of this before posting read our [rules of conduct](https://github.com/AR-js-org/AR.js/blob/master/CODE_OF_CONDUCT.md), i will post here some key points:
- Using welcoming and inclusive language
- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community
- Showing empathy towards other community members
