### ISSUE TITLE
Problem with the example

### ISSUE THREAD

**Issue by Deja-vuuu** [AR-js-org/AR.js#421]
https://ar-js-org.github.io/AR.js/aframe/examples/image-tracking/nft/  

Loading, please wait...

ios 15.4.1
safari

**Comment by saiprabhu-bk** [comment]
I also have the same issue with iPhone SE 2020 (iOS 15.5)

**Comment by Deja-vuuu** [comment]
> I also have the same issue with iPhone SE 2020 (iOS 15.5)
You can try my example. I'm running normally here.
https://github.com/Deja-vuuu/AR.js-demo
