### ISSUE TITLE
Hiro pattern not found in aframe example

### ISSUE THREAD

**Issue by kalwalt** [AR-js-org/AR.js#43]
**Do you want to request a *feature* or report a *bug*?**
It's a bug: hiro pattern is not loaded see the error reported in the section below.

**What is the current behavior?**
Open the **marker-events.html** example in the console you will see:
`aframe-ar.js:1622 GET http://localhost:3000/examples/marker-training/examples/pattern-files/pattern-hiro.patt 404 (Not Found)`
This happens running on localhost, not tested on codepen or other env.
**If the current behavior is a bug, please provide the steps to reproduce.**
See the comment above.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Tested on Desktop Ubuntu 18.04.03
**What is the expected behavior?**
Pointing the Hiro marker to the camera, it should be showed a cube and a rotating torus.
**If this is a feature request, what is motivation or use case for changing the behavior?**
No feature request, only fixing a bug.

**Comment by kalwalt** [comment]
it happens also on the online site https://ar-js-org.github.io/AR.js/aframe/examples/marker-based/marker-events.html

**Comment by kalwalt** [comment]
@nicolocarpignoli This also happens for most of the aframe **marker_based** examples ( only the basic example is not affected.

**Comment by nicolocarpignoli** [comment]
Im away from pc.you should find the differences between the one working and not. Maybe some changes with paths? Do not know without check

**Comment by kalwalt** [comment]
> Im away from pc.you should find the differences between the one working and not. Maybe some changes with paths? Do not know without check

The **basic** example is not affected because probably id the only one is using an `<a-anchor>` tag, all the other examples use `<a-marker>` instead.

**Comment by kalwalt** [comment]
because in component-anchor.js hiro pattern is defined in this way:

```js
markerParameters.patternUrl = THREEx.ArToolkitContext.baseURL + 'examples/marker-training/examples/pattern-files/pattern-hiro.patt'

```
i think that is the error. Probably changing the name of the folder examples. :slightly_smiling_face:

**Comment by kalwalt** [comment]
This will fix for the hiro pattern:

```diff
- markerParameters.patternUrl = THREEx.ArToolkitContext.baseURL + 'examples/marker-training/examples/pattern-files/pattern-hiro.patt'
+ markerParameters.patternUrl = THREEx.ArToolkitContext.baseURL + 'data/data/patt.hiro'
```
I'm going to fix this, also kanji pattern need it.

**Comment by kalwalt** [comment]
That fixed but maybe should more correct: 

```diff
- markerParameters.patternUrl = THREEx.ArToolkitContext.baseURL + 'examples/marker-training/examples/pattern-files/pattern-hiro.patt'
+ markerParameters.patternUrl = THREEx.ArToolkitContext.baseURL + 'three.js/examples/marker-training/examples/pattern-files/pattern-hiro.patt'

```
based on the changes in this commit https://github.com/jeromeetienne/AR.js/commit/32e1e29d8cb28ec20682d4e089ad75af10bf5bb9#diff-d6e4c48405c28cfbbe2952ef505ed7f6

**Comment by kalwalt** [comment]
This seems to fix but, i get another error:
```js
aframe-ar.min.js:1 GET https://ar-js-org.github.io/data/data/camera_para.dat 404
aframe-ar.min.js:1 Error: supplied file does not appear to be an ARToolKit camera parameter file.
aframe-ar.min.js:1 loadCamera(): Error loading parameter file /camera_param_0 for camera.
```

**Comment by kalwalt** [comment]
As a final note this not happens in the three.js examples....

**Comment by kalwalt** [comment]
Testing codepen example https://codepen.io/kalwalt/pen/VwLrPrz

**Comment by kalwalt** [comment]
I'm testing also here in this repository see https://github.com/kalwalt/testing-AR.js-libs/issues/1

**Comment by kalwalt** [comment]
To solve definetely this issue we could think to embed **hiro** and **kanji** patterns inside the AR.js core. Actually we can't do this because require a little modification of jsartoolkit5. For now we can read a Patterm Marker with **loadMarker**

https://github.com/artoolkitx/jsartoolkit5/blob/244b2b23286403e78fa24805b34509dc5a88052f/js/artoolkit.api.js#L556 

see how is defined in ARToolkitJS.cpp 

https://github.com/artoolkitx/jsartoolkit5/blob/244b2b23286403e78fa24805b34509dc5a88052f/emscripten/ARToolKitJS.cpp#L472-L481

the marker is loaded thanks to the **arPattLoad** : 

https://github.com/artoolkit/ARToolKit5/blob/5bf0b671ff16ead527b9b892e6aeb1a2771f97be/lib/SRC/AR/arPattLoad.c#L143-L157

but it exist also **arPattloadFromBuffer** https://github.com/artoolkit/ARToolKit5/blob/5bf0b671ff16ead527b9b892e6aeb1a2771f97be/lib/SRC/AR/arPattLoad.c#L54-L141
so instead to load from a file we can load a Pattern from a Buffer. I think we can do this and will definetely solve this issue.

**Comment by nicolocarpignoli** [comment]
fixed?

**Comment by kalwalt** [comment]
Yes i think we fixed it. Regarding to my last comment in the thread we will see if it make sense or if we can foind another solution.

**Comment by nicolocarpignoli** [comment]
okay we can close for now and re use this discussion in the future if needed.
