### ISSUE TITLE
wrong path in cameraParametersUrl in threex-artoolkitcontext.js

### ISSUE THREAD

**Issue by kalwalt** [AR-js-org/AR.js#44]
**Do you want to request a *feature* or report a *bug*?**
Trying to fix another bug #43 i found this one. 

**What is the current behavior?**
in threex-artoolkitcontext.js there is this line:
https://github.com/AR-js-org/AR.js/blob/c2a780aca9f6ad60c432ef6f1eaf7fa9d74cbbac/three.js/src/threex/threex-artoolkitcontext.js#L21

but it is wrong because point to non existent path.

**If the current behavior is a bug, please provide the steps to reproduce.**
Do this, in dev example comment out this line:
https://github.com/AR-js-org/AR.js/blob/c2a780aca9f6ad60c432ef6f1eaf7fa9d74cbbac/three.js/examples/dev.html#L101

in this way you will force to use the path from **threex-artoolkitcontext.js**, and you will receive this error:
```js
artoolkit.api.js:1603 GET http://localhost:3000/three.js/parameters/camera_para.dat 404 (Not Found)
artoolkit.min.js:1 Error: supplied file does not appear to be an ARToolKit camera parameter file.
artoolkit.min.js:1 loadCamera(): Error loading parameter file /camera_param_0 for camera.
artoolkit.min.js:1 Allocated videoFrameSize 172800
artoolkit.min.js:18 Uncaught 
ExitStatus {name: "ExitStatus", message: "Program terminated with exit(0)", status: 0
```
to solve we need to change the path for **cameraParametersUrl** in this way:

`cameraParametersUrl: ARjs.Context.baseURL + '../data/data/camera_para.dat',`

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Tested on Desktop localhost (ubuntu 18.04.03)
**What is the expected behavior?**
It should load the default camera parameters.

**Comment by kalwalt** [comment]
I will fix tomorrow this.

**Comment by nicolocarpignoli** [comment]
Great job @kalwalt, i'm closing this as you solved on the linked PR.

**Comment by kalwalt** [comment]
yes, i think it was a very old isue indeed.

**Comment by kalwalt** [comment]
In the future we can consider also another solution for deafult data configuration, it would be useful have a config file where to store all this settings and so a user can easily changes the default settings. See for example the Ogre engine or other project has a similar approach. I will open a separate issue for this feature.

**Comment by Samar3dgeneralists** [comment]
Facing an similar issue the above solution not working or might be i am doing wrong, can anyone give me the Solution, here is the error i am seen on my screen.
![error 2023-05-12 162419](https://github.com/AR-js-org/AR.js/assets/108662625/59ff032e-a523-45a0-a836-a383561c0274)

**Comment by kalwalt** [comment]
> Facing an similar issue the above solution not working or might be i am doing wrong, can anyone give me the Solution, here is the error i am seen on my screen. ![error 2023-05-12 162419](https://user-images.githubusercontent.com/108662625/237951499-59ff032e-a523-45a0-a836-a383561c0274.png)

This issue is closed and you have already posted in a new issue here #539 !!

Please don't double posting!
