### ISSUE TITLE
The smoothingfactor dont work, how to fix shaking on location based 3d model?

### ISSUE THREAD

**Issue by MilosGlisovic** [AR-js-org/AR.js#446]
When I apply this code from docs ` <a-camera  look-controls-enabled='false' arjs-look-controls='smoothingFactor: 0.1' gps-camera='gpsMinDistance: 20' rotation-reader>>
            </a-camera>`  3D model dont show, if I delete look controls and arjs look controls 3d work but with shaking. What is the best way to fix the shake with smoothinkg factor or some other way in location based 3d gltf model?

**Comment by nickw1** [comment]
@MilosGlisovic this isn't just because of the double >> in your code?

**Comment by MilosGlisovic** [comment]
It still doesn't show 3d models, this is my code and when I delete look controls and arjs look controls then show my 3d but with shaking and when I set this attribut they dont show any 3d.

` <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
        <script src="https://raw.githack.com/jeromeetienne/AR.js/master/aframe/build/aframe-ar.min.js"></script>
        <script src="https://raw.githack.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
        <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
       
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        
        <script>
            THREEx.ArToolkitContext.baseURL = 'https://raw.githack.com/jeromeetienne/ar.js/master/three.js/'
        </script>
    </head>
    <link rel="stylesheet" href="index2.css">
    <script src="places2.js"></script>
    <body style='margin: 0; overflow: hidden;'>
        <a-scene
        cursor='rayOrigin: mouse; fuse: true; fuseTimeout: 0;'
            raycaster="objects: [gps-entity-place];"
           vr-mode-ui="enabled: false"
           gesture-detector
           id="scene"
            embedded
            arjs='sourceType: webcam; sourceWidth:1280; sourceHeight:960; displayWidth: 1280; displayHeight: 960; debugUIEnabled: false;'>
            <a-camera look-controls-enabled='false' arjs-look-controls='smoothingFactor: 0.1' gps-camera rotation-reader> </a-camera>
        </a-scene>
    </body>
</html>`

**Comment by nickw1** [comment]
This code looks quite old to me (the AR.js link is for AR.js 2 I think).
Have you tried adapting this example instead?

https://github.com/AR-js-org/AR.js/tree/master/aframe/examples/new-location-based

**Comment by nickw1** [comment]
Also (sorry) the `smoothingFactor` is not yet implemented with the `new-location-based` controls.

You could also look at the original `location-based` components here:
https://github.com/AR-js-org/AR.js/tree/master/aframe/examples/location-based

**Comment by MilosGlisovic** [comment]
I tried with the new version of ar.js and with the same code from the example from the link, but it's still the same, do you know what it is? Is there another way to use smoothingfactor or some other attribute to reduce jitter? I also have a question about positioning, what is the best way to adjust the position value so that the 3d is as close to the ground as possible? Thanks in advance

**Comment by nickw1** [comment]
I've noticed you're using an `embedded` scene, I don't think that works. That's quite an old example, it's better to use the newer examples.

At some point (if I have the time) I will fix the new `location-based` components to remove the shaking but as you can hopefully appreciate that depends on my time availability. But if you use the `gps-projected-camera` and `gps-projected-entity-place` components from the original `location-based` components it should work, AFAIK.

Regarding placing the object on the ground, that's a difficult problem involving plane detection. I am investigating/researching this but this will take some significant time to implement.

**Comment by nickw1** [comment]
@MilosGlisovic just to update, the smoothing is now ported to the `new-location-based` components as a PR (#483), hopefully will be merged soon.

**Comment by nickw1** [comment]
Fixed by #483, so closing.
