### ISSUE TITLE
DeviceOrientationControls undefined this.orientationChangeEventName 

### ISSUE THREAD

**Issue by spoxies** [AR-js-org/AR.js#465]
**Do you want to request a *feature* or report a *bug*?**

**Bug**:

Currently using `ar-threex-location-only.js` and possibly `aframe-ar-location-only.js` an error will be trigged from within `class DeviceOrientationControls extends EventDispatcher {}`  There is a small scope error as `this.orientationChangeEventName` is called from a nested function but the var is defined a scope higher.

**Reproduce**:

Use DeviceOrientationControls using `ar-threex-location-only.js` and possibly `aframe-ar-location-only.js` and there will be an this.orientationChangeEventName undefined error
```javascript
...
const camera = new THREE.PerspectiveCamera(80, 2, 0.1, 50000);
const deviceOrientationControls = new THREEx.DeviceOrientationControls(camera);
....
```

This issue belongs to PR https://github.com/AR-js-org/AR.js/pull/464

**Comment by nickw1** [comment]
@spoxies merged #464 so this should now be fixed.
