### ISSUE TITLE
gps-new-camera iOS Errors

### ISSUE THREAD

**Issue by D4ve-R** [AR-js-org/AR.js#470]
**Do you want to request a *feature* or report a *bug*?**

Bug Report

**What is the current behavior?**

2 Errors while running the [new-location-based example](https://github.com/AR-js-org/AR.js/blob/master/aframe/examples/new-location-based/index.html) in Safari
using :
```
<a-camera gps-new-camera ></a-camera>
```

![thiselsceneELError](https://user-images.githubusercontent.com/69651599/197898066-4021e272-f9c0-4791-b49a-8e6f063442f3.png)

![Bildschirmfoto 2022-10-25 um 23 40 43](https://user-images.githubusercontent.com/69651599/197898102-e3ba7d52-6e16-4bf5-be20-582688b34eec.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Running the example on Safari or with browser devTools userAgent set to Apple/Safari devices

**Please mention other relevant information such as the browser version, Operating System and Device Name**

Safari Issue

**What is the expected behavior?**

No Errors

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by D4ve-R** [comment]
Solved by Pull Request #471

**Comment by nickw1** [comment]
@D4ve-R have merged PR, will now close this. Thanks for the fix!
