### ISSUE TITLE
Which is the Three.js version?

### ISSUE THREAD

**Issue by atlasan** [AR-js-org/AR.js#472]
Hi there! And thank you for this amazing project.
I'm using a three.js template and I need to load some extra stuff for three.js but I can't find which version should I work with.. the AR.js included version works great, but the last three.js version would not work for me (trying to include FBXloader)

Thank you in advance!

**Comment by atlasan** [comment]
install via npm, than look in node_modules/three ...

**Comment by kalwalt** [comment]
Hi @atlasan You can see three.js version in the package.json https://github.com/AR-js-org/AR.js/blob/0722816b2afaf327186e40e38e1de454a3f5d434/package.json#L64
I updated the three.js version in PR #469 I hope soon to merge it.
