### ISSUE TITLE
android WebRTC Issue - Navigator.MediaDevice is not presented in your device

### ISSUE THREAD

**Issue by qianxifu** [AR-js-org/AR.js#480]
hi, when i trying to run the example "three.js/examples/dev.html" i got thr error: WebRTC Issue - Navigator.MediaDevice is not presented in your device

my device information is below
OS: android 12
Brower: chrome

i have granted the app the access to the camera.

can anyone give me some help? thanks a lot.

[https://github.com/qianxifu/myImages/blob/main/arjs_20221207145341.jpg](url)

**Comment by kalwalt** [comment]
Hi @qianxifu that's strange, what device type are you using?

**Comment by qianxifu** [comment]
@kalwalt i solved it. it must access with https
