### ISSUE TITLE
[Android : Chrome, Firefox] navigator.mediadevices not present ( fixed format )

### ISSUE THREAD

**Issue by TheBricktop** [AR-js-org/AR.js#49]
**Do you want to request a *feature* or report a *bug*?**
reporting a bug probably

**What is the current behavior?**
After serving the template index locally and checking on the mobile browser im getting a message that my browser doestn have navigator mediadevices ( tested on chrome and firefox )
**If the current behavior is a bug, please provide the steps to reproduce.**
- copy and paste the example into index.html
- serve locally 
- check on android

Using the template from readme so thats plausible.
**Please mention other relevant information such as the browser version, Operating System and Device Name**
Android Chrome and Firefox
**What is the expected behavior?**
It actually starts and shows feed from camera after asking for permissions
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
Hi @TheBricktop can you test this codepen https://codepen.io/kalwalt/pen/zYGRRYd ? Tell us if something changes.

**Comment by TheBricktop** [comment]
Yes it works as intended (also much faster than the last version )

**Comment by kalwalt** [comment]
> Yes it works as intended (also much faster than the last version )

Thank you! :smile: Much faster in comparison of which version ?

**Comment by TheBricktop** [comment]
I was testing  Your early version of jsartoolkit-nft and it was laggy at times but now its much faster
