### ISSUE TITLE
[bug report] gps-new-entity-place distance property unavailable

### ISSUE THREAD

**Issue by marcusx2** [AR-js-org/AR.js#502]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

The [documentation](https://ar-js-org.github.io/AR.js-Docs/location-based/) talks about the distance property. I can't find it anywhere.

**If the current behavior is a bug, please provide the steps to reproduce.**

I tried

`entity.getAttribute('gps-new-entity-place')`
`entity.getDOMAttribute('gps-new-entity-place')`
`entity.components['gps-new-entity-place'].data`

None of them display the `distance` property, only longitude and latitude.

**What is the expected behavior?**

To show the distance property which is the current distance from the camera. The documentation says the `gps-new-entity-place` component has this property, but I'm unable to find it.

**Comment by nickw1** [comment]
This isn't a bug. The `distance` is not part of the component schema but a simple property of the `gps-new-entity-place` component.

Use `entity.components['gps-new-entity-place'].distance`.

**Comment by nickw1** [comment]
To follow up, see this example: https://github.com/AR-js-org/AR.js/tree/master/aframe/examples/new-location-based/show-distance

Look inside `clicker.js`.

**Comment by marcusx2** [comment]
You have to move to a new location after arjs started for the distance to be calculated. However this shouldn't be the case, because after starting the experience you already have the user's position and the entity's position. It's a bug, isn't it? How is the distance calculated, can you give me the formula? Thanks.

**Comment by nickw1** [comment]
Sorry, it sounded from your original post that you were not accessing the component the correct way.

When you start the experience you might not necessarily have the position, as it might take time to obtain a new GPS position. 

However may be you are right - if the GPS position is known when the experience is started, you can calculate the distance. I'll look into it when I have the moment, apologies if I misunderstood.

**Comment by nickw1** [comment]
... to update, the distance calculation is done in `gps-new-entity-place` (https://github.com/AR-js-org/AR.js/blob/master/aframe/src/new-location-based/gps-new-entity-place.js) in the `_haversineDist()` method, so if you want to fix yourself before the next release, look in there.

**Comment by nickw1** [comment]
#507 solves this.

**Comment by marcusx2** [comment]
I still get undefined

```
<!DOCTYPE html>
<html>
<head>
<title>AR.js A-Frame Location-based</title>
<script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
<script type='text/javascript' src='https://raw.githack.com/AR-js-org/AR.js/master/three.js/build/ar-threex-location-only.js'></script>
<script type='text/javascript' src='https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js'></script>
</head>
<body>
<a-scene vr-mode-ui='enabled: false' arjs='sourceType: webcam; videoTexture: false; debugUIEnabled: false' renderer='antialias: true; alpha: true'>
    <a-camera look-controls-enabled='false' arjs-device-orientation-controls='smoothingFactor: 0.1' gps-new-camera='positionMinAccuracy: 100; gpsMinDistance: 5; simulateLatitude: 51.049; simulateLongitude: -0.723; simulateAltitude: 0; gpsTimeInterval: 0;' position='0 10 0'></a-camera>
    <a-entity material='color: red' geometry='primitive: box' gps-new-entity-place="latitude: 51.05; longitude: -0.72" scale="100 100 100" ></a-entity>
</a-scene>
<script>
    const entity = document.querySelector("[gps-new-entity-place]");
    console.log(entity.components['gps-new-entity-place'].distance);//returns undefined
	setTimeout(() => {
		console.log(entity.components['gps-new-entity-place'].distance);//returns distance
	}, 0);
</script>
</body>
</html>
```

**Comment by nickw1** [comment]
The PR hasn't been merged yet.

To test it you'll need to check out the `distance-fix` branch and use that.

**Comment by nickw1** [comment]
@marcusx2 I've checked the code example you gave above with the `distance-fix` branch and it works, it gives a distance of around 237m.
