### ISSUE TITLE
The demo link is not loading

### ISSUE THREAD

**Issue by drveresh** [AR-js-org/AR.js#510]
This demo [link](https://ar-js-org.github.io/AR.js/aframe/examples/image-tracking/nft/) isn't working, just showing "Loading, please wait..." forever.

**Comment by alanwong0922** [comment]
I have the same problem too. 
I am using the iPad Air  (4th gen) ios 15.4

**Comment by amymila** [comment]
same from samsung galaxy note 9 and windows pc... always loading please wait

**Comment by emnul** [comment]
Doesn't work on my Mac or iPhone either

**Comment by kalwalt** [comment]
Updated with a new link in the [Readme](https://github.com/AR-js-org/AR.js/blob/master/README.md) see commit https://github.com/AR-js-org/AR.js/commit/8609ac9689e0e9a4c0bfc44ea6ca7ae795b1da81
