### ISSUE TITLE
visual glitches in 3d objects on mobile chrome and firefox

### ISSUE THREAD

**Issue by TheBricktop** [AR-js-org/AR.js#52]
Downloaded the latest one

**Do you want to request a *feature* or report a *bug*?**
Buggity

**What is the current behavior?**
Tried both on mobile chrome and firefox 
Currently on Samsung Galaxy s8, 3d objects have weird flickering glitches probably caused by something in compositing of the scene on video feed.
Happens also on desktop and with the examples provided from readme ex with Trex model.
![Screenshot_20200314-215919_Firefox](https://user-images.githubusercontent.com/3866030/76690469-809e0080-6640-11ea-822b-b06478c8fec1.jpg)

**If the current behavior is a bug, please provide the steps to reproduce.**
1.entered the codepen.io example on mobile browser.
2. Saw that 
![Screenshot_20200314-221422_Chrome](https://user-images.githubusercontent.com/3866030/76690546-5436b400-6641-11ea-981d-e9a8249eacb3.jpg)

The one from the readme of ar.js 

Yes on the Trex one.
**Please mention other relevant information such as the browser version, Operating System and Device Name**
Android Samsung Galaxy S8 Firefox and  chrome.
**What is the expected behavior?**
The Tris on 3d objects shouldn't flicker
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
@TheBricktop Probably it depends by the dpi and resolution of  NFT marker. I will provide another one with better quality. Thanks for testing! :slightly_smiling_face:

**Comment by kalwalt** [comment]
@TheBricktop we changed the NFT marker for the Trex example can you test it, please? :smile:

**Comment by TheBricktop** [comment]
Well the nature of the flicker suggest that there is a problem with either the clipping plane of the camera or there is a conflict between the render layers of 3d and video feed.
The resolution of the marker shouldnt be the issue.
Can You reproduce the artifacts on your side?

**Comment by nicolocarpignoli** [comment]
@TheBricktop can you try again with the codepen on the readme, now?

i had that problem if not adding `renderer="logarithmicDepthBuffer: true;"` on the a-scene

**Comment by Kulcanhez** [comment]
@kalwalt trex image on readme.md needs to be updated for the big one :)

**Comment by nicolocarpignoli** [comment]
> @kalwalt trex image on readme.md needs to be updated for the big one :)

done :)

**Comment by TheBricktop** [comment]
@nicolocarpignoli  that was probably it no glitches on the trex so now im testing my website

**Comment by nicolocarpignoli** [comment]
Close the issue if it's solved for you.
