### ISSUE TITLE
Web Assembly support for NFT

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/AR.js#53]
**Do you want to request a *feature* or report a *bug*?**

Enhancement request

**What is the current behavior?**

AR.js (jsartoolkit5 to be precise) can use Web Assembly for NFT (image tracking).
It has better performances: https://docs.google.com/spreadsheets/u/1/d/1FykKO1dkPz0zUVuJCOPA2tHIs0Zs3nUybjLJcKihfs4/edit#gid=0

We should think of using it as default, in the future @kalwalt

**Comment by kalwalt** [comment]
yes, and also use only one jsartoolkit5 lib, leaving the old one.

**Comment by kalwalt** [comment]
I think we can close this as new Emscripten versions deploy **ONLY** Wasm files and consequently asm.js is a very old feature. AR.js with the ES6 feature because depends on artoolkit5-js and we load only the wasm ES6 version we can definetely close this issue.
