### ISSUE TITLE
Facing an issue the, here is the error i am seen on my screen, please help

### ISSUE THREAD

**Issue by Samar3dgeneralists** [AR-js-org/AR.js#539]
![error 2023-05-12 162419](https://github.com/AR-js-org/AR.js/assets/108662625/c4979499-a4e7-4388-bd4f-bbd02e6a2714)

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by Samar3dgeneralists** [comment]
was solved from server side

**Comment by kalwalt** [comment]
@Samar3dgeneralists as i can see from the log you are using an old AR.js version. We don't support anymore the `artoolkit.min.js` and `artoolkit.api.js` files. Please switch to the latest AR.js version. 
And to help other potential user fill all the requested entry in the issue with a detailed description of the problem you encountered, and some more informations: AR.js version, your OS...
