### ISSUE TITLE
Image Tracking not working

### ISSUE THREAD

**Issue by SirAlejandroMartinez** [AR-js-org/AR.js#551]
Hey guys. Just testing the image tracking at is says Loading all the time.
¿Can you provide me an alternative to the example at the web that works at the momment?
I would like to use image tracking using a lot of different images.

**Comment by kalwalt** [comment]
please test the example here https://github.com/AR-js-org

**Comment by kalwalt** [comment]
see PR https://github.com/AR-js-org/AR.js-Docs/pull/21 and issue #569
