### ISSUE TITLE
Location based: which version and component variant works accurately?

### ISSUE THREAD

**Issue by Platform-Group** [AR-js-org/AR.js#552]
**Do you want to request a *feature* or report a *bug*?**

I have a litany of bugs

**What is the current behavior?**

new-location-based with a-frame:

1. Camera is stretched
2. Incorrect true north despite both test devices having compass sensor
3. On first load where permissions are given, black screen appears and refresh required
4. Often randomly decides to throw up a white screen instead of a camera, no apparent console logs/errors or events to detect failure. Often need to close tab and browser and open fresh to fix.
5. Simulated lat and long are ignored when location data is turned on

classic:

Latitude and longitude of entities or location data is seemingly ignored as everything is placed directly on top of the camera, filling the screen with entities and text.

projected with three.js:

1. The box is inaccurately placed and doesn't track properly with the camera movement (it drifts a little with the camera turn instead of staying on a fixed locations)
2. The canvas is only a letterbox, using css to make the canvas use the full height and width seems to remove entities

**If the current behavior is a bug, please provide the steps to reproduce.**

a-frame example: https://gentle-closed-element.glitch.me/

<script
      type="text/javascript"
      src="https://aframe.io/releases/1.4.2/aframe.min.js"
    ></script>
    <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
    <script
      type="text/javascript"
      src="https://www.unpkg.com/@ar-js-org/ar.js@3.4.5/three.js/build/ar-threex-location-only.js"
    ></script>
    <script
      type="text/javascript"
      src="https://www.unpkg.com/@ar-js-org/ar.js@3.4.5/aframe/build/aframe-ar.js"
    ></script>

Simple entity placement on lat and long

**Please mention other relevant information such as the browser version, Operating System and Device Name**

Poco F5 is my main device, but I also borrowed an iPhone (no idea which version) just to check it wasn't my phone, and it has the same issues.

**What is the expected behavior?**

From scrolling through this repo, I've seen most of these bugs mentioned before in issues. However workarounds or fixes don't seem to be provided. As it stands the current version appears to be unusable as I'm unable to accurately place entities, this is the biggest issue by far. And I can't find any working older versions either.

_Can anyone provide me a simple location based example that works accurately?_ 

Or alternatively, is there a method to manually and accurately calibrate which direction is north, so that I don't even need location data as what I want to build will be used at a set location.

**Comment by Platform-Group** [comment]
Closing this because it's not constructive and was written out of frustration

**Comment by beachgrub** [comment]
This is correct on iOS. I have tried the simple examples and they work fine on android but not on iOS. This was closed incorrectly IMO.

**Comment by nickw1** [comment]
The issue is that most of the maintainers lack iOS devices. We'd really welcome maintainers who own an iDevice as it's difficult to verify pull requests or detect iOS-related bugs without them. Also applies to #547 and #590.

So if there are any owners of iOS devices willing to contribute to maintaining the project, please let us know.

**Comment by beachgrub** [comment]
It turned out the fix proposed to use the Heading for orientation is not correct. The iOS handles heading very strangely. I had to grab the heading once at startup and use that as offset to the device orientation. Even that is not totally correct if the user has phone flat at start. So still working on a robust solution but will advise.
