### ISSUE TITLE
move arToolkitSource.domElement to another parent?

### ISSUE THREAD

**Issue by dw-herrmann** [AR-js-org/AR.js#565]
Hi there, 
I want to build arjs into a div, so it's just a frame on my website, instead of full screen. I found out, how to append the video tag to my container, but it still creates a second one inside the body.

```` js
arToolkitSource.init(function onReady() {
  frame.appendChild(arToolkitSource.domElement);
})
````
Html structure:
``` html
<body>
  <frame>
      <video />
  </frame>
  <video />
</body>
```
How can I remove the video element inside <body> the correct way?

Edit: I use the threejs version of it

**Comment by Platform-Group** [comment]
I do it by putting the arjs code in its own iFrame, and you can just use css

video {
  display: none;
}

As the arjs output is from the canvas anyway

**Comment by Platform-Group** [comment]
@dw-herrmann that would break it as the video element stream is being used by the canvas, I'm not sure why it's done that way but it is. The normal AR.js functionality has the canvas fullscreen at a higher z-level so you just never see the video element behind it, setting the video to display none is just another step forward from that.

**Comment by dw-herrmann** [comment]
@Platform-Group, that's strange. This code works fine for me and breaks nothing

``` js
arToolkitSource.current.init(function onReady() {
	nextFrame = requestAnimationFrame(animate);
	frame.appendChild(arToolkitSource.domElement); // move video from body to frame
	setTimeout(() => { // remove video element after 2 seconds
		let videoElement = document.querySelector("body>#arjs-video");
		if (videoElement) videoElement.remove();
	}, 2000);
})
```

**Comment by Platform-Group** [comment]
@dw-herrmann that's not the video element's id in my code, at least I've never seen an element called #arjs-video before. It simply looks like: `<video autoplay="true" playsinline="true" display="none"></video>` to me, and deleting that breaks the video stream.

I've never used arToolkitSource with arjs though, I use aframe and I'm guessing you must be using threex.

Glad you've found a working solution though.

**Comment by dw-herrmann** [comment]
Ah, that's the difference! I should have said that in the beginning :D

At first, I tried aframe but noticed, there is no way to make a react-component out of it, because it puts everything into the body.
