### ISSUE TITLE
Mouse click/touch on object not working with Aframe 0.9.0 and later

### ISSUE THREAD

**Issue by yannklein** [AR-js-org/AR.js#57]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Aframe-ar issue: Mouse click/touch on objects using <a-marker preset="hiro" cursor='rayOrigin: mouse;'> is not working with aframe v.0.9.0 and more (working okay with v0.8.0).

**If the current behavior is a bug, please provide the steps to reproduce.**
Use this [code](https://github.com/yannklein/aframe-ar-workshop/blob/master/steps/Step-4%20Links%20and%20video%20with%20AR.html).
It is working okay with 
`<script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>`
but not with
`<script src="https://aframe.io/releases/1.0.0/aframe.min.js"></script>`

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Tested on Laptop (Mac) with Chrome/Firefox and Mobile (iPhone), with Safari.

**What is the expected behavior?**
Click working.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
Hi @yannklein i can see that in your code are you using the old repo, does it happens a also with the code with the [new 3.0.0 version](https://github.com/AR-js-org/AR.js/releases/tag/3.0.0) ? Also as stated in the docs [here](https://ar-js-org.github.io/AR.js-Docs/ui-events/) should works until aframe 0.9.2

**Comment by yannklein** [comment]
@kalwalt you guys did a great job, it works like a charm with v3.0.0 and aframe v0.9.2 :)
Little warning for aframe v1.0.0, it seems not to work in that case as of today. 
Thank you for your answer, the new releases and the great doc 👍we can close that issue

**Comment by kalwalt** [comment]
> @kalwalt you guys did a great job, it works like a charm with v3.0.0 and aframe v0.9.2 :)
> Little warning for aframe v1.0.0, it seems not to work in that case as of today.
> Thank you for your answer, the new releases and the great doc we can close that issue

Happy for this! @nicolocarpignoli did a great job with the docs indeed!
