### ISSUE TITLE
Image tracking AR.js with React stuck on loading screen , please help!

### ISSUE THREAD

**Issue by bubleygum** [AR-js-org/AR.js#578]
**Do you want to request a *feature* or report a *bug*?**
bug?

**What is the current behavior?**
it's stuck on loading screen with lots of warning but no error 
**If the current behavior is a bug, please provide the steps to reproduce.**
https://bubleygum.github.io/Logic-pwa8/

**Please mention other relevant information such as the browser version, Operating System and Device Name**
chrome
**What is the expected behavior?**
not stuck?
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
Hi @bubleygum if you read the last line it's clear that is something wrong with your nft marker path:
```
Error in loading marker on Worker
code
: 
"ERR_BAD_REQUEST"
config
: 
{transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
message
: 
"Request failed with status code 404"
name
: 
"AxiosError"
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
response
: 
{data: ArrayBuffer(9379), status: 404, statusText: '', headers: cA, config: {…}, …}
stack
: 
"AxiosError: Request failed with status code 404\n    at blob:https://bubleygum.github.io/20397c4e-ad0f-4a3b-a657-2a5feca880cc:1:752024\n    at XMLHttpRequest.a (blob:https://bubleygum.github.io/20397c4e-ad0f-4a3b-a657-2a5feca880cc:1:752169)"
[[Prototype]]
: 
Error
```
Please also add more informations to the issue.

**Comment by bubleygum** [comment]
i resolved it in local, by puting the <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"></script>outside the <body></body> but somehow it didn't work on github
