### ISSUE TITLE
change "Twitter" to "𝕏 (Twitter)" in README.md

### ISSUE THREAD

**Issue by BandhiyaHardik** [AR-js-org/AR.js#580]
**Do you want to request a *feature* or report a *bug*?**
Twitter is now known as 𝕏.

**What is the current behavior?**
![image](https://github.com/AR-js-org/AR.js/assets/110784317/adb70ca6-5e6d-49cf-90b6-21ae9ad10f1f)

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**
![image](https://github.com/AR-js-org/AR.js/assets/110784317/20466f1d-834f-4603-8f57-9f02734a9fb2)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
Yes you are right @BandhiyaHardik i will review your PR #581

**Comment by BandhiyaHardik** [comment]
Completed via https://github.com/AR-js-org/AR.js/pull/581

**Comment by kalwalt** [comment]
Thank you @BandhiyaHardik for your contribution!
