### ISSUE TITLE
Document is so misleading

### ISSUE THREAD

**Issue by allestaire** [AR-js-org/AR.js#587]
Damn, documentation is so misleading, dont know the options of arjs
ttsk tsk

**Comment by Matimateokol** [comment]
Hi 👋, I'm not yet a part of the project but I would like to contribute and help you in any possible way. I think starting with project documentation is a good entry point.💪 I find the project very interesting to me and a very promising, disruptive technology in next few years. 

@allestaire I've just noticed your ticket during searching for open issues and see that you've got troubles with comprehending the documentation.

Could you maybe pinpoint parts of the documentation that you find misleading to you? :) Maybe that way we and other users can enhance it by extending it, making it more specific, concise amd/or more readable. 
For instance: what do you mean by AR.js options? Do you mean AR.js features or possible configurations?

**Comment by Matimateokol** [comment]
I think this issue is highly related to #562  and can be continued there...
