### ISSUE TITLE
bug with rotation 

### ISSUE THREAD

**Issue by kalwalt** [AR-js-org/AR.js#59]
**Do you want to request a *feature* or report a *bug*?**
This is a bug, due to cleaning the code while upgrading version.

**What is the current behavior?**
Normally in **AR.js** you should adjust the position of 3D object with the **y** value. but now you have to adjust the **z** value.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just try one of the examples ( basic.html, dev.html in three.js examples folder) the Pattern Marker examples.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
This happens on every kind of device, but i tested for now only on desktop.

**What is the expected behavior?**
if you want to display a plane onto the marker with a texture, you will see that the texture is rotated by 90 degree on the right.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Restoring the standard behaviour.
The cause was deleting this part of the code in **threex-armarkercontrols.js**:

https://github.com/jeromeetienne/AR.js/blob/024318c67121bd57045186b83b42f10c6560a34a/three.js/src/threex/threex-armarkercontrols.js#L130-L135

that make rotating on **X** axis. Restoring this part of the code will solve the issue. A PR is on the way,  You can check my working branch https://github.com/kalwalt/AR.js-org/tree/feature-artoolkit-new

In the meantime to solve the rotation issue try to rotate the mesh:

`mesh.rotation.x = 0.5*Math.PI;`

**Comment by kalwalt** [comment]
To understand the issue see these two pictures:
This happens with the new 3.0.0 version
![aframe-ar-new](https://user-images.githubusercontent.com/1275858/76881588-aa8e3780-6879-11ea-9601-6368bd9f295f.png)
this was instead the orignal version with Ar.js 2.2.2:
![old-aframe-ar](https://user-images.githubusercontent.com/1275858/76881725-df01f380-6879-11ea-8feb-2a3449de62cb.png)
dont look at the text but tat the glitched texture ( it is the same displayed on the left top corner)
I'm not sure that my suggestion `mesh.rotation.x = 0.5*Math.PI;` will work i think instead you should multiply the matrix.

**Comment by fcor** [comment]
Not sure if it's the same issue, but I was updating some stuff from older AR.js version to 3.0 and I had to rotate the a-entity 90deg on X axis to make it look as expected when rendering on top a traditional hiro marker

**Comment by kalwalt** [comment]
@fcor yes exactly because we missed an important part see PR https://github.com/AR-js-org/AR.js/pull/60 with this commit https://github.com/AR-js-org/AR.js/pull/60/commits/66caf7a6d575e54f277a91ae996520a85bf7bbe2 at lines https://github.com/kalwalt/AR.js-org/blob/c18346bd9c16677fbdc342fb564629c5a09dbda3/three.js/src/threex/threex-armarkercontrols.js#L119-L121
Would you test the PR? This will be nice to merge before the AR.js/studio  release... :slightly_smiling_face:

**Comment by fcor** [comment]
@kalwalt Sure! I'll give it a try 😃

**Comment by kalwalt** [comment]
> @kalwalt Sure! I'll give it a try

Thank you! :smile:

**Comment by kalwalt** [comment]
This is merged in the `dev` branch #60, waiting to be merged in master.
