### ISSUE TITLE
NTF not working for me with my own image

### ISSUE THREAD

**Issue by meowtec** [AR-js-org/AR.js#61]
**Do you want to request a *feature* or report a *bug*?**
A bug maybe.

Here is my picture and the traning result:
https://user-images.githubusercontent.com/4006436/76956552-37ef8b80-694f-11ea-9883-5f1d3ea1fc70.png
https://t.newscdn.cn/webar-demo/0.0.1/AR.js-master/aframe/new-demo/bingtangxueli.[ext]

The example page is:
https://t.newscdn.cn/webar-demo/0.0.1/AR.js-master/aframe/new-demo/btxl.html

**What is the current behavior?**

When I scanned my image, I should see red text `BingTang`, but nothing.

While the official NFT files `nft/trex/trex-image/trex` work fine.

And I also can see some log info like `Tracked page 15794352 (max 0).` in Chrome. I think it means that 
the image was recognized successfully. But I don't know why the text was not rendered. Please help me.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Open link: https://t.newscdn.cn/webar-demo/0.0.1/AR.js-master/aframe/new-demo/btxl.html
2. Scan image: https://user-images.githubusercontent.com/4006436/76956552-37ef8b80-694f-11ea-9883-5f1d3ea1fc70.png

**Please mention other relevant information such as the browser version, Operating System and Device Name**

Device: Huawei Honer 9X
UserAgent:
```
Mozilla/5.0 (Linux; Android 9; HLK-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.96 Mobile Safari/537.36
```

**What is the expected behavior?**
I should see red text `BingTang`

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment]
I think that is not a bug. the image is tracked, but you should change the position of the `<a-text> `probably is outside of view or maybe need to be rotated. Can say so much at the moment , but for sure the NFT marker works. I will try in a codepen later.

**Comment by kalwalt** [comment]
You need only to encrease the scale of the `<a-text>` try this codepen https://codepen.io/kalwalt/pen/qBdKYrW

**Comment by meowtec** [comment]
@kalwalt Thanks a lot!

I can see the text only when my camera is very close to the picture. It becomes invisible when my camera moves a little further.

**Comment by kalwalt** [comment]
> I can see the text only when my camera is very close to the picture. It becomes invisible when my camera moves a little further.

This depends from the quality of the image, It will have sufficient descriptors only when at full size. The NFT-Marker-Creator create a series of gray images at different resolution from the highest dpi (provided by the info included in the image) to the lower possible, every gray image has his detection and tracking points. detection points are used in the first stage of the image tracking, tracking points in the second. If the detections number points are low it will difficult to detect the image. 
Not all the images are well suited for this, probably this image that has flat colours and low detail is not   the best, but as you can see it can be tracked. Even if has good dimensions in pixels (3242X1342) this is not sufficient . You could increase the dpi in your image editor (gimp or other) and try to create other NFT descriptors. But i think won't cahnge so much...
Try instead with other types of images, and read carefully the wiki https://github.com/Carnaux/NFT-Marker-Creator/wiki/Creating-good-markers and my article: https://www.kalwaltart.com/blog/2020/02/25/tutorial-create-marker-NFT/

**Comment by meowtec** [comment]
@kalwalt Thank you! I will try with some other pictures.
