### ISSUE TITLE
Alternative NFT marker generator

### ISSUE THREAD

**Issue by anuj9196** [AR-js-org/AR.js#614]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
https://github.com/Carnaux/NFT-Marker-Creator
Current documented NFT Marker Generator has not activity from last 3 years. I want a marker generator that can generate marker using python script in the server. I do not want web UI for this. I tried to dockerize the existing NFT marker generator but facing few issues.

**If the current behavior is a bug, please provide the steps to reproduce.**
Currently documented marker generator does not support generation using python (I want it to generate in Django application).

**Comment by kalwalt** [comment]
Hi @anuj9196 I have developed a independent project in our [WebARKit organization](https://github.com/webarkit) called [Nft-Marker-Creator-App](https://github.com/webarkit/Nft-Marker-Creator-App) It's quite updated, but maybe need some upgrades in the code. Test it and let me know how it goes.
In regards of your question `Currently documented marker generator does not support generation using python` yes you are correct at the moment it's not possible, but, technically speaking it should be possible to compile C/C++ code to python thanks to emscripten, but i have no experience at all. Probably it is possible but i can not say a release date, of course. We can discuss this in the [issue tracker](https://github.com/webarkit/Nft-Marker-Creator-App/issues) of the original repository.
