### ISSUE TITLE
How can I get the size and the center position of the image when using NFT?

### ISSUE THREAD

**Issue by faace** [AR-js-org/AR.js#64]
**Do you want to request a feature or report a bug?**
It's a feature request.

**What is the current behavior?**
NFT works but it is difficult to locate the position of the image. When I move the image a bit more, the position of the a-ntf moves a little.
And we don't know the width and the height of the image.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Is it possible to know the position of the center of the image and the size of the image, just like the marker tracking?

**Comment by JamesBotterill** [comment]
This is coming in an update to the ARjsToolkit. @kalwalt has it in his sights

**Comment by kalwalt** [comment]
Yes this is on my plans/sights closing because already posted #4
