### ISSUE TITLE
WebRTC issue when using example code on own site but not on demo url

### ISSUE THREAD

**Issue by roverb** [AR-js-org/AR.js#67]
So I tried the demo with the marker and it worked just fine but when copying the code that was under the link for the example it didn't work. So I thought I could maybe try to get it to work by copying all the code from the demo site, which I did but I still got the same error.
The url I was testing it on:
http://thenot.nl/ar
The demo:
https://ar-js-org.github.io/AR.js/aframe/examples/marker-based/basic.html

I'm using it on my Samsung Galaxy S8 with Chrome 80.0.something and Android 9.

**Comment by kalwalt** [comment]
Hi @roverb, This happens also on desktop. Also are you hosting on a site without `https` maybe this comment will help you https://github.com/jeromeetienne/AR.js/issues/463#issuecomment-503552278
