### ISSUE TITLE
Removing old jsartoolkit5 version from AR.js 

### ISSUE THREAD

**Issue by kalwalt** [AR-js-org/AR.js#68]
**Do you want to request a *feature* or report a *bug*?**
This a feature request and also an enhancement of **AR.js**

**What is the current behavior?**
Actually we have two types of **AR.js** libs as described in the [AR-js-org docs](https://ar-js-org.github.io/AR.js-Docs/) 

1. **Image Tracking** and **Location Based**  >> (ar-nft.js and aframe-ar-nft.js)
2.  the old style lib for **Pattern Marker**; **Barcode Marker**... >>  (ar.js  and aframe-ar.js)

The first one use the newest jsartoolkit5 lib, the second use the old jsartoolkit5 lib with .min and .api bundled together.

Why this? artoolkit.api.js is required otherwise you will get this issue on Mobile device (portrait mode) see https://github.com/AR-js-org/AR.js/pull/60#issuecomment-600755818 and also pay attention to all the discussion in the PR https://github.com/AR-js-org/AR.js/pull/60
We need to remove the old lib because we can not add new features to jsartoolkit5.

**If the current behavior is a bug, please provide the steps to reproduce.**
remove artoolkit.api.js from the compilation ([Makefile](https://github.com/AR-js-org/AR.js/blob/master/three.js/Makefile)) ,

```diff
- cat vendor/jsartoolkit5/build/artoolkit.min.js \
- vendor/jsartoolkit5/js/artoolkit.api.js >> build/ar.js

+ cat vendor/jsartoolkit5/build/artoolkit.min.js >> build/ar.js
```

 run the script, test the basic example or any other example on portrait mode (Mobile)

**Please mention other relevant information such as the browser version, Operating System and Device Name**
The bug i mentioned occurs only in portrait mode (Mobile)
**What is the expected behavior?**
Eliminating artoolkit.api.js should behave in the same way.
**If this is a feature request, what is motivation or use case for changing the behavior?**
Upgrading **AR.js** to the new jsartoolkit5 ( not only for nft).

**Comment by kalwalt** [comment]
I solved the problem, but i think we have to find a better solution. I will explain now all the aspect of the issue. As mentioned above, the problem arises when you are in `'portrait'` mode (on Mobile) without the **artooolkit.api.js**.

Why this? 

In the old and also in the new (with NFT)  artoolkit.api.js at the beginning, when a new ARController is instantiated theere is:
https://github.com/AR-js-org/AR.js/blob/da5ea830211c323a41ebd55a97b99f85add1cd40/three.js/vendor/jsartoolkit5/js/artoolkit.api.js#L31
this is the default setting. When you run a **jsartoolkit5** code and you are in portrait mode `this.orientation` becomes `'portrait'` because in ARController.getUserMediaARController 
https://github.com/AR-js-org/AR.js/blob/da5ea830211c323a41ebd55a97b99f85add1cd40/three.js/vendor/jsartoolkit5/js/artoolkit.api.js#L1292-L1296
if the video width is less than height `this.orientation = 'portrait'`, but because getUserMediaARController is never used inside AR.js ( treex-arcontroller, threex-artoolkitsource and so on...) `this.orientation` is always `landscape` !! see my comment here https://github.com/AR-js-org/AR.js/pull/60#issuecomment-601671876

So what is the solution? 

This issue was already in the old Ar.js lib see this changes in this [PR](https://github.com/jeromeetienne/AR.js/pull/212) in artoolkit.api.js about the portait mode inside the **_copyImageToHeap**  
I tested adding that changes to the new artoolkit.api.js in this way:

```js
  if( (image.nodeName === 'IMG' && image.width > image.height ) ||
	      		(image.nodeName === 'VIDEO' && image.videoWidth > image.videoHeight) ){
			        // if landscape
	                        this.ctx.drawImage(image, 0, 0, this.canvas.width, this.canvas.height); // draw video
		        }else{
			        // if portrait
			        this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
		        	var scale = this.canvas.height / this.canvas.width;
			        var scaledHeight = this.canvas.width*scale;
		        	var scaledWidth = this.canvas.height*scale;
			        var marginLeft = ( this.canvas.width - scaledWidth)/2;
			        this.ctx.drawImage(image, marginLeft, 0, scaledWidth, scaledHeight); // draw video
		         }
```
instead of:

```js

               if (this.orientation === 'portrait') {
			this.ctx.translate(this.canvas.width, 0);
			this.ctx.rotate(Math.PI/2);
			this.ctx.drawImage(image, 0, 0, this.canvas.height, this.canvas.width); // draw video
		} else {
			this.ctx.drawImage(image, 0, 0, this.canvas.width, this.canvas.height); // draw video
		}
```
Apllying that changes and rebuilding the jsartoolkit5 libs solve this issue. Anyway i will prefer to not apply that cahnges to the jsartoolkit5 and find another solution.
More to come...

**Comment by kalwalt** [comment]
If someone want to test the modified **jsartoolkit5**  version, as i explained in the previous comment, may grab the **artoolkit.min.js** from this branch https://github.com/kalwalt/jsartoolkit5/tree/fix-copyImageToHeap, and modify the [Makefile](https://github.com/AR-js-org/AR.js/blob/master/three.js/Makefile) as i explained in the comment at the top. After test the threejs basic example. other examples require to delete the artoolkit.api.js script import.

**Comment by kalwalt** [comment]
i have a testing **AR.js** [branch](https://github.com/kalwalt/AR.js-org/tree/testing-feature-artoolkit-new-v1)  on my repository, testing is welcome!!

**Comment by hatsumatsu** [comment]
> getUserMediaARController is never used inside AR.js

@kalwalt Just curious, what's the reason to not use it in AR.js?

**Comment by kalwalt** [comment]
I suppose, because i didn't the first implementation of the lib, that the reason is Aframe, probably require a particular set-up, but i'm not a great expert with Aframe. Or maybe a deliberate code design choice?
