### ISSUE TITLE
URL for Image tracking using NFT

### ISSUE THREAD

**Issue by shubhamraghav1** [AR-js-org/AR.js#71]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

While using NFT as per your codes you used a URL so if i want to use my own image how would i do this.... or how would i load those files "fset, fset3, iset"

**Comment by Kulcanhez** [comment]
@shubhamraghav1 you can read the documentation (https://ar-js-org.github.io/AR.js-Docs/image-tracking/) it's all there. :)

**Comment by kalwalt** [comment]
Hi @shubhamraghav1 as said by @Kulcanhez you should read the docs at https://ar-js-org.github.io/AR.js-Docs/image-tracking/  Please, before posting an issue here always read the docs !
Generally we should use the issue tracker for issue regarding the code (bugs, ideas how to improve...). For general questions use also [stackoverflow](https://stackoverflow.com/) i will answer there if i can. We are also opening a slack channel, we will let you know.

**Comment by Rodrigosik** [comment]
Good morning everyone, I have a problem that I have been looking for and I cannot find any solution
It's about the URL attribute
url='https://rutadeldominio.com/src/marker/palomitas_ntf/palomitas'
for example when I do this it does not work for me it says that it cannot find the images nft 404

but on my localhost when I put it like this
url='src/marker/palomitas_ntf/palomitas'

it doesn't work either
I can't find a way to fix it

**Comment by kalwalt** [comment]
@Rodrigosik are you sure that the url and the path is correct? have you a github repository to look at? It's a bit difficult to help without inspecting the code and the file structure...
