### ISSUE TITLE
How to setup custom qr-code in marker tag

### ISSUE THREAD

**Issue by abhithakkar19** [AR-js-org/AR.js#73]
As I already implemented custom patterns in my project now I want to implement custom qr-code scanning also. So for that I have already followed the below link:

https://medium.com/chialab-open-source/how-to-deliver-ar-on-the-web-only-with-a-qr-code-e24b7b61f8cb

And I have also made marker in qr-code from this links

for barcode: https://au.gmented.com/app/marker/marker.php
for marker in qr-code: https://www.qrcode-monkey.com/

But the problem is I don't know how to use this qr-code which i made. Do i need to create a patt file of it and used it in the marker tag? but at the same time I thought that would be for type = 'pattern'.

So can any one please help me out in how to implement custom bar-code scanning in the code.

**Comment by nicolocarpignoli** [comment]
yes you need to use the marker pattern (.patt) as usual. The only thing is that your marker is at the center of a QR Code.

If you follow the article you will have all informations you need.

Please write on https://gitter.im/AR-js/Lobby for troubleshooting, issues are for bugs/feature requests

Thanks
