### ISSUE TITLE
3D model off centre from marker

### ISSUE THREAD

**Issue by oninross** [AR-js-org/AR.js#76]
**To Reproduce**
Since the upgrade of aframe to 1.0.4, the 3D objects that are being projected on the marker are off center and does not behave as expected.  See screenshot below: 
![Screen_Shot_2020-04-07_at_3_38_43_pm__2_](https://user-images.githubusercontent.com/2233813/78633997-41cd3480-78e6-11ea-9398-8118a3877779.png)

**Expected behavior**
The screenshot below says it all
![Screen_Shot_2020-04-07_at_3_42_40_pm__2_](https://user-images.githubusercontent.com/2233813/78634112-8a84ed80-78e6-11ea-9185-7d03966e976a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Chrome Version 80.0.3987.149 

**Additional context**
It would be nice just to use 1 version of the plugin and not 2 different versions.  I have a small project that uses AR markers and AR Geolocation

**Comment by kalwalt** [comment]
Hi @oninross, Reading from your code i can see that you are using the old repository you should use instead this one:

`<script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js">`

as explained from the docs:

https://ar-js-org.github.io/AR.js-Docs/

github repository:

https://github.com/AR-js-org/AR.js-Docs

**Comment by oninross** [comment]
Thank you!  So sorry I forgot to place the link to the codepen.  Here it is though: https://codepen.io/oninross/pen/oNXKqdy

I did update the repo link for aframe-ar and its a bit ok now compared last time.  Its still offset from the centre and behaving quite weirdly when you twist and turn the marker
![Screen Shot 2020-04-08 at 11 25 46 am (2)](https://user-images.githubusercontent.com/2233813/78734511-d50c7580-798b-11ea-800d-9672a3b2c92f.png)

**Comment by kalwalt** [comment]
Don't use `<a-marker-camera>` use instead `<a-entity-camera>` and displace the `<a-box>` on the z axis.  Example codepen with aframe 0.9.2 https://codepen.io/kalwalt/pen/xxGWBao but will work also with aframe 1.0.4.  Until this PR https://github.com/AR-js-org/AR.js/pull/60 is not merged you have to displace the mesh on z axis.

**Comment by dderom** [comment]
I do have the same issue though. 

All 3D models are offset from the center of the marker, and the larger the model the bigger the offset becomes. I tried with [gltf models](https://github.com/dderom/expo-dko/blob/main/public/exhibitions/rodin/index.html), and equally with [simple a-boxes](https://github.com/dderom/expo-dko/blob/main/public/exhibitions/sculpture/index.html). 

Same behaviour on:
Desktop:
- Chrome Version 89.0.4389.114 (Official Build) (arm64)
- Firefox 87.0 (64-bits)
- Safari Version 14.0.2 (16610.3.7.1.9)

Android 10
- Chrome: 89.0.4389.105

iPad:
- Safari
