### ISSUE TITLE
glft-modell does not animating

### ISSUE THREAD

**Issue by GaT11** [AR-js-org/AR.js#81]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
My 3D-Modell isn't animating with the animation-mixer
**If the current behavior is a bug, please provide the steps to reproduce.**
--

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Version 80.0.3987.163 (Offizieller Build) (64-Bit), Windows 10 Education
**What is the expected behavior?**
I don't know
**If this is a feature request, what is motivation or use case for changing the behavior?**
--

**Comment by GaT11** [comment]
And i have another issue.
My gltf-modell isn't animating like it should but the 3D-Model appears on screen.
Can you please help me an write another Code that works into this Chat?

Here's my code:

               <a-entity 
               gltf-model="url(bilder_ar/steve-gltf/scene.gltf)"  
               animation-mixer="clip:Armature.001; loop:2; timeScale: 5; 
               crossFadeDuration: 1">
               </a-entity>

**Comment by GaT11** [comment]
I have solved the Problem

**Comment by kalwalt** [comment]
Hi @GaT11, welcome in the AR.js issue tracker, please when you post/ask a question you are invited to do these things:

-  fill all the sections in the issue template with all the infos.
- If you find a solution post the solution.
- if the post is solved edit the original title with a **`[ SOLVED ]`** label.

This will help other devs, users,  people to take benefit from issues, I hope that you understand, Thanks! :smile:

**Comment by SajjaadSherif** [comment]
how was this resolved? I am facing the same issue
