### ISSUE TITLE
black screen instead of video screen

### ISSUE THREAD

**Issue by GaT11** [AR-js-org/AR.js#83]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
 When I'll insert a video in Augmented Reality only a black screen appears on the display. The video doesn't appear.
**If the current behavior is a bug, please provide the steps to reproduce.**
In the next message my code is given

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Chrome: Version 80.0.3987.163 (Offizieller Build) (64-Bit), Windows 10 Education, 
**What is the expected behavior?**
I don't know
**If this is a feature request, what is motivation or use case for changing the behavior?**
--

**Comment by GaT11** [comment]
Hello I have a probleme. When I'll insert a video in Augmented Reality only a black screen appears on the display.
Can you help me, please?

There's my code:
     
    <!doctype HTML>
    <html>
    <script src="https://aframe.io/releases/0.6.1/aframe.min.js"></script>
    <script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/build/aframe-ar.js">
    </script>

    <body style='margin : 0px; overflow: hidden;'>
        <a-scene embedded arjs>
            <a-marker preset="hiro">
                <a-video position='0 0.1 0' rotation='270 0 0' scale='1 0.5 1' src='/sv.mp4'></a-video>
            </a-marker>
            <a-entity camera></a-entity>
        </a-scene>
    </body>

    </html>
I am just getting a black screen instead of video.

**Comment by JamesBotterill** [comment]
I'd look at the video example in the examples folder, I wouldn't load in the video via src and use the a-assets component instead. You'd also need to make sure it's muted for it to autoplay due to browser limitations.
