### ISSUE TITLE
Add "markerLost" event for THREEx artoolkitControls

### ISSUE THREAD

**Issue by ToufMar** [AR-js-org/AR.js#84]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I'm working with the Three / Threex version not de A-Frame one.

When I set a addEventListener("markerLost", () => console.log("marker lost") i have nothing whereas with  addEventListener("markerFound", () => console.log("marker found") the log is displayed.

You can reproduce it on the nft.html example in three.js just add listeners.
```javascript
 var markerControls = new THREEx.ArMarkerControls(arToolkitContext, camera, {

            type: 'nft',
            descriptorsUrl: 'data/dataNFT/pinball',
            changeMatrixMode: 'cameraTransformMatrix'
        })
        markerControls.addEventListener('markerFound', () => {
            console.log("hey");
        })
        markerControls.addEventListener('markerLost', () => {
            console.log("nope");
        })
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Operating System and Device Name**

**What is the expected behavior?**
addEventListener("markerLost", (event) => //get event);
**If this is a feature request, what is motivation or use case for changing the behavior?**
I need this feature to display a target on my screen when marker is lost ..
Thx for every things guys, this lib is awesome !!

**Comment by kalwalt** [comment]
Hi @ToufMar Are you refering only to NFT for this? Probably this happens because NFT has a different listeners in jsartoolkit5 https://github.com/artoolkitx/jsartoolkit5/blob/244b2b23286403e78fa24805b34509dc5a88052f/js/artoolkit.api.js#L267-L314 I will check this.

**Comment by kalwalt** [comment]
I think you are right in arMarkerControl we have only **markerFound** event:
https://github.com/AR-js-org/AR.js/blob/master/three.js/src/threex/threex-armarkercontrols.js#L173

**Comment by kalwalt** [comment]
We could try to add a dispatch event here https://github.com/AR-js-org/AR.js/blob/da5ea830211c323a41ebd55a97b99f85add1cd40/three.js/src/threex/threex-armarkercontrols-nft-start.js#L356-L359

something like this:

```javascript
} else {
          _this.context.arController.showObject = false;
          // dispatchEvent
          this.dispatchEvent({ type: 'markerLost' });
     } 
```
what do you think @nicolocarpignoli ?

**Comment by nicolocarpignoli** [comment]
@kalwalt absolutely correct. we can add it on https://github.com/AR-js-org/AR.js/pull/98 if not already done

**Comment by kalwalt** [comment]
The problem is that if i add **markerLost** in that manner, it will be dispatced only for **NFT**. Instead the dispatced event **markerFound** is dispatched for every markers type (Pattern, Barcode, Multi...) found.

**Comment by ThomasRutzer** [comment]
@kalwalt Any chance to dispatch this event for all markers? Should it be fired in this [code section](https://github.com/AR-js-org/AR.js/blob/master/three.js/src/threex/threex-armarkercontrols.js#L247)?

**Comment by nicolocarpignoli** [comment]
available now on dev branch: https://github.com/AR-js-org/AR.js/pull/225
