### ISSUE TITLE
Using Videos instead of 3D models

### ISSUE THREAD

**Issue by DayMKay** [AR-js-org/AR.js#93]
**Question:**
Is there a way to usw videos instead of 3D models - if yes: where do I find a documentary about this?

**Comment by kalwalt** [comment]
We have not documentation for this, but you can look at the [`<a-nft>` video example](https://github.com/AR-js-org/AR.js/blob/master/aframe/examples/image-tracking/nft-video/index.html)

**Comment by DayMKay** [comment]
Great! Thanks for this quick respond :-)

**Comment by DayMKay** [comment]
This code works perfectly fine but it is muted. If I remove "muted playsinline" then the autoplay doesnt start anymore :( How can I remove the silence without crashing your code? :/

**Comment by JamesBotterill** [comment]
> This code works perfectly fine but it is muted. If I remove "muted playsinline" then the autoplay doesnt start anymore :( How can I remove the silence without crashing your code? :/

Not possible on modern browsers don't allow unmuted video to autoplay

**Comment by DayMKay** [comment]
I realised, that the video doesnt start on the first try but let me see just a picture. If I swing to camera to another point and come back to the marker point the video starts. Seems like a problem that could be solved, but I dont know how ... Maybe with an event "start video on click"?

**Comment by kalwalt** [comment]
> Maybe with an event "start video on click"?
I could be, but with which device are you testing?

**Comment by DayMKay** [comment]
I am using a smartphone with android. My current solution is to start it muted and to unmute it with a click. This works fine for me but is not ideal for the audience I have in mind (kids). Would be great if there would be a workaround. But every solution without an user intput seems to be canceled instantly. So thanks for all your help.

**Comment by JamesBotterill** [comment]
I add a start screen which meets the page interaction and means you can autoplay with the video unmuted.

I work on a product and we had to do this to solve the issue, it's a pain but better than those horrible video ads playing 😡

**Comment by nicolocarpignoli** [comment]
We can close this, it is a browser issues, not AR.js. Thanks
