### ISSUE TITLE
Custom Event For Image descriptor or NFT data loading complete

### ISSUE THREAD

**Issue by codeisindna** [AR-js-org/AR.js#97]
Any custom event is there for completion of the loading of NFT data?, the camera-init custom event will fire when the camera is initialized, but there is no event when loading of NFT data is complete.
In colsole I can see "**d40fd298-7299-42a3-910e-48f6310d242f:5 [info] Loading of NFT data complete**" but how to listen for this event using javascript?

**Features to be added**
We want some custom event that will fire when the loading of NFT data is completed.

**Comment by nicolocarpignoli** [comment]
Yes, there is a custom event fired internally: https://ar-js-org.github.io/AR.js-Docs/ui-events/ you can read here at the bottom.

We can expose it, for sure. @kalwalt I think it's pretty simple to do and we can do that also on next release 3.1.0 with no big effort

**Comment by kalwalt** [comment]
> We can expose it, for sure. @kalwalt I think it's pretty simple to do and we can do that also on next release 3.1.0 with no big effort

yes i can do if you want for this release. I will start to work tomorrow if i have time. :slightly_smiling_face:

**Comment by nicolocarpignoli** [comment]
That will be great!

**Comment by kalwalt** [comment]
Please @codeisindna test PR #98

**Comment by codeisindna** [comment]
I have tested the PR on android and ios, both are working fine I am able to get "arjs-nft-loaded" custom event listener.
**Test Device Info**
**Android**
Browser: Chrome
Android Version:10

**Ios**
Browser: Safari
Os version: 13.3.1

Please merge with a master branch so everybody can use it normally.

One thing I will like to mention is that This is not an Issue this is just a feature we all want.

Once merged let me know I will close this issue

Thank you for adding this feature to us :).

**Comment by nicolocarpignoli** [comment]
great. @kalwalt you can merge on dev branch and update CHANGELOG :)

You can close this issue as soon as it's merged on dev

**Comment by codeisindna** [comment]
Ok, once it's merged, let me know and I will close the issue
Thank you.

**Comment by codeisindna** [comment]
Thank you for adding this feature :)

**Comment by kalwalt** [comment]
@nicolocarpignoli i will update the docs if you have not updated with this new Event.

**Comment by nicolocarpignoli** [comment]
@kalwalt yes please, and then deploy them too :)
